### ISSUE TITLE
Extend port switch to handle multiple ports

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#100]
If we know we host ssh endpoints on mixed ports (say 22 and 2222) we might want to scan both port 22 and 2222 in a single scan.

Expected usage would be like...

scan_ssh -f hosts.txt -p 22,2222

If #99 existed, a socket specification in the file would override the port-based "bruteforce".

**Comment by jinankjain** [comment]
#160  Fixes #100 too.
