### ISSUE TITLE
Define default client key_init message as an object rather than raw blob

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#104]
This is really just to make sure we're being clear about what's being sent in the initial client key init message and leaving it open to be expanded upon in the future.  The string blob isn't all that transparent.

Make the following definition manually defined as a SSHScan::KeyExchangeInit object...

https://github.com/mozilla/ssh_scan/blob/master/lib/ssh_scan/constants.rb#L8-L21

Example:

    default_key_init = SSHScan::KeyExchangeInit.new()
    ...set all attributes manually...

**Comment by jinankjain** [comment]
@claudijd I did not exactly get you, what are you trying to say in this bug. So you want in constants.rb redefine DEFAULT_KEY_INIT_RAW by SSHScan::KeyExchangeInit.new() and then set the properties manually?

**Comment by claudijd** [comment]
yes, exactly.  I want what we send to be built using  SSHScan::KeyExchangeInit.new()  rahter than being a string blob.
