### ISSUE TITLE
Set a default max thread pool and expose the ability for users to control it

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#115]
Currently, if we're given 100,000 IPs to scan, we'll continue to thread those out until we run out of memory.  We should have some sane limit on how big that thread pool should get at any given time for not only preservation of the scanner, but also preservation of the network we're scanning.

Recommended default threads should be something under 10.

**Comment by claudijd** [comment]
@jinankjain FYI, since you worked on some of the threading stuff.

**Comment by jinankjain** [comment]
@claudijd I was thinking about this case when I was writing that patch, at some point we would like to keep a limit on our thread pool. Idea would be to create a pool of 10 threads and distribute work depending upon when threads are free

**Comment by jinankjain** [comment]
@claudijd Time to close. It's a great day we have crossed a lot of things out of TODO List.

**Comment by claudijd** [comment]
Fixed in #121 (apologies for collision), same approach though :)

**Comment by jinankjain** [comment]
It's fine @claudijd I kind of explored threading in Ruby starting to like Ruby more than Python 😉

**Comment by claudijd** [comment]
@jinankjain welcome to the dark side :)

**Comment by jinankjain** [comment]
@claudijd I recently got to know ssh_scan is taking part in MWoS 2016, I would love to take part in that.

**Comment by claudijd** [comment]
@jinankjain cool, see this blog post for details https://blog.mozilla.org/security/2016/08/01/announcing-mwos-2016/
