### ISSUE TITLE
Multi-ip scans don't properly handle CIDR notation

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#116]
I went to run a test scan on a local network range and ran into this issue...

    $ ./bin/ssh_scan -t 192.168.10.0/24
    /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/socket.rb:54:in `connect_nonblock': Permission denied - connect(2) for 192.168.10.0:22 (Errno::EACCES)
    	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/socket.rb:54:in `connect_internal'
    	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/socket.rb:140:in `connect'
    	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/socket.rb:338:in `block in tcp'
    	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/socket.rb:232:in `each'
    	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/socket.rb:232:in `foreach'
    	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/socket.rb:328:in `tcp'
    	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/client.rb:27:in `connect'
    	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:14:in `scan_target'
    	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:80:in `block (2 levels) in scan'

192.168.10.0 is a network address and not a routable address for a /24 CIDR notation.  When computing CIDR notations, we need to only talk to viable addressable hosts in that range.  For 192.168.10.0, this would be 192.168.10.1 - 192.168.10.254 as .255 would be the broadcast for that range.

**Comment by jinankjain** [comment]
@claudijd Gotcha I know how to fix this patch is on it's way 😄
