### ISSUE TITLE
Add Gitter for ssh_scan

### ISSUE THREAD

**Issue by jinankjain** [mozilla/ssh_scan#118]
Gitter room would be a good place to discuss new features and we should have it for ssh_scan.

**Comment by claudijd** [comment]
I've never used Gitter, mostly use Mozilla's IRC chat (https://wiki.mozilla.org/IRC)

If you think Gitter will add some value, please feel free to set it up and we can invite people who are active on the project.  An alternative would be that I could create an IRC chatroom for #ssh_scan, but I'm open to either.

**Comment by jinankjain** [comment]
Previously I was working with some mozillascience project, they were using Gitter. I kind of liked it more than IRC we could try out Gitter.

**Comment by claudijd** [comment]
Sounds good to me, you are welcome to create the space and we can invite ssh_scan contribs.

**Comment by jinankjain** [comment]
@claudijd Seems like only you can create that room for ssh_scan because you are the owner for that repository.

**Comment by claudijd** [comment]
@jinankjain I'll get it setup then.  Thanks!

**Comment by claudijd** [comment]
@jinankjain I'm just an admin on this repo and not at the org level (I'll need to summon a GitHub).

@ulfr do you think you could authorize Gitter to see data for the ssh_scan repository? @jinankjain wants to try it out for ssh_scan to discuss features and try out something different.

**Comment by jinankjain** [comment]
@claudijd Thanks!

**Comment by jinankjain** [comment]
@claudijd Any updates on this?

**Comment by claudijd** [comment]
302 to @jvehent

**Comment by jvehent** [comment]
Is this what you need? https://gitter.im/mozilla-ssh_scan/Lobby#

**Comment by jinankjain** [comment]
@jvehent Yeah that's what we need 😄

**Comment by jinankjain** [comment]
@jvehent Thanks for the help 😄
