### ISSUE TITLE
Add unit-test coverage for PolicyManager object

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#127]
We don't have any unit-test coverage for PolicyManager class.

Here's what would be expected to resolve this issue...

1.) Create a file spec/ssh_scan/policy_manager_spec.rb
2.) Add various tests that exercise examples of policy compliance and non-compliance to ensure it works as expected.  (this should also include error cases, like what happens when we're missing the information we need)

**Comment by flash1452** [comment]
@claudijd  I would like to work on this bug.

**Comment by jinankjain** [comment]
@flash1452 Thanks for the PR. Awesome work 👍

**Comment by claudijd** [comment]
yeah, thanks @flash1452 we'll send you some greets on the next release iteration
