### ISSUE TITLE
Potential port bug found in already merged #125

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#130]
https://github.com/mozilla/ssh_scan/pull/125

https://github.com/mozilla/ssh_scan/commit/18e958d7f9ca9347cf0bda2ba7ab304dc84de592#diff-903158d449f10b1aac623831242f53e1R41

@jinankjain said...

"@royalharsh @claudijd I have a doubt here with -p as an argument we directly pass port that would applied to all the passed target not just the last one."

**Comment by royalharsh** [comment]
Does this mean while doing this
```bash
./bin/ssh_scan -t ssh.mozilla.com,github.com -p 2222
```
We want port as 2222 for only github.com and not for ssh.mozilla.com? @claudijd

**Comment by jinankjain** [comment]
We want for both @royalharsh

**Comment by claudijd** [comment]
This is probably a good time to call out what our expectations should be for how ports are applied in various scenarios so we can ensure we have tests that verify these cases....

**Easy Scenarios**
1. User does -t scan with no -p port specification
- all targets via -t will be scanned on port 22
2.) User does -t scan with -p port specification
- all targets via -t will be scanned via -p port specification, example 22222
3.) User does -t scan with -p multiple port specification
- all targets via -t will be scanned via all ports in -p port specification, example 22,22222
4.) User does -f scan with no -p port specification
- all targets via -f file will be scanned on port 22
5.) User does -f scan with -p port specification
- all targets via -f file will be scanned via -p port specification, example 22222

**Harder Scenarios**
1. User does -f scan with -p port specification and targets in -f also contain :port specifications
- ??? I think -f :port specification should override -p specification
2.) User does -t scan and -f scan at the same time
- ??? should throw an exception making options mutually exclusive
3.) User does -t scan with socket inputs (example: github.com:22)
- ??? I dunno
...INSERT_MORE - we can discuss and then implement specs that ensure it behaves the way we want to.

**Comment by jinankjain** [comment]
@claudijd For harder scenarios I think there is a way out

-  User does -f scan with -p port specification and targets in -f also contain :port specifications. Instead of overriding the ports we could create a set which do union of both the port specification. Same applies for -t and -f together

**Comment by claudijd** [comment]
Another idea would be to consider the following...

-t  and -f flags triggers an exception (can't use them together)
-p and socket-based targets (via -t or -f) triggers an exception (can't use them together)

This could vastly simplify the above, but either way I think it's possible.  Just need feedback on what makes the most sense.

**Comment by claudijd** [comment]
@jinankjain that works for me

**Comment by claudijd** [comment]
@royalharsh this should result in the following sockets...

./bin/ssh_scan -t ssh.mozilla.com,github.com -p 2222

ssh.mozilla.com:2222
github.com:2222

where are this would test both...

./bin/ssh_scan -t ssh.mozilla.com,github.com -p 22,2222

ssh.mozilla.com:22
ssh.mozilla.com:2222
github.com:22
github.com:2222

....

**Comment by royalharsh** [comment]
Thanks for clarifying my doubt. :) I'll take a look at it.
