### ISSUE TITLE
Update gem version from 0.0.9 to 0.0.10

### ISSUE THREAD

**Issue by jinankjain** [mozilla/ssh_scan#133]

**Comment by claudijd** [comment]
I noticed this earlier today and updated the release notes for 0.0.10.

**Comment by claudijd** [comment]
Fixed here and retroactively in all other release notes...

https://github.com/mozilla/ssh_scan/releases/tag/0.0.10

In short, I was in a hurry on Friday because I forgot to release on Wednesday and missed a few steps, like publishing the 0.0.10 version.

**Comment by claudijd** [comment]
https://github.com/mozilla/ssh_scan/blob/master/lib/ssh_scan/version.rb

**Comment by claudijd** [comment]
I'm also already preparing release notes for 0.0.11, which I hope to release tomorrow.  Release frequency is expected to slow down as the project reaches more maturity.  But I'll keep up weekly as long as there are fixes/features being added.

**Comment by jinankjain** [comment]
Yeah that's how big project grows
