### ISSUE TITLE
Work around SSH verifier bugs that cause net-ssh to freak out

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#135]
net-ssh has an SSH verifier class that's used to control how it handles ssh key re-usage.  Unfortunately for ssh_scan, this means that ssh_scan will litter the known hosts file on the system you scan from and will also throw exceptions when you find another host using the same key.

Fixing this issue would likely need the following items:

1.) Prevent net-ssh for littering the scanners ssh host key store (this might require a custom verifier object we'd need to pass net-ssh)

**Comment by jinankjain** [comment]
@claudijd setting :paranoid parameter to false would work?

**Comment by claudijd** [comment]
@jinankjain that's what I tried on a test scan of about 2,000 SSH endpoints, but I ran into issues with host-key re-usage and host-key's being nil when we inspected for host key fingerprint generation.  Some details of this are in #22.

I really hope that is the case, but I have a hunch that more will be required.

**Comment by jinankjain** [comment]
@claudijd I looked at the verifier code in net-ssh they raise error only when it don't find the host key in it's host key database.

**Comment by claudijd** [comment]
@jinankjain ok, then maybe we can do a PR and test it out again on my 2K hosts and see if it still complains and just trap the exception case when it's not already in the host-key db.  Or maybe we could write our own custom verifier type to get the behavior we want.

**Comment by claudijd** [comment]
Here's an example....

Add this to your ssh authorized_keys file...

    85.62.141.172 ssh-rsa AAAAB3NzaC1yc2EAAAABAwAAAQEAwE4k9wtQAVbskQuADsAmgBg9qnNDL0cl7aXlnFGh0jOXWKaxbxphDUVBd//sdlPu7TpGN00hYwaA/r/58IcnL+4VjllFP93luc8UxH/W7OBhQGpbt77qHdE0LuL1fRwIGOseIbDNC4xeTNdnVpRQJZ7jT7j6a7h4/8c6Un470mILAeX9wC4W0wmNm9u+x/MCP2RCRh9VB/EcOxIjQznc/Q56ABL881lIjHvEBdCtKXVEpdVt9GM4Rcpa/XrRPTvrQXKxtSnYXm3a8swGKjOyDimnOun29nt38NyrGdypNNxhnoDwc4CRCh93IqY32nP2ydzedCqd8JoM0lb5/EAUAQ==

And then scan this host and get this....

    $ ./bin/ssh_scan -t 85.62.141.172
    I, [2016-09-16T12:43:51.611974 #11709]  INFO -- : Started ssh_scan of 85.62.141.172
    /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/verifiers/secure.rb:48:in `process_cache_miss': fingerprint 16:8a:d0:17:e5:ff:b8:54:dd:b6:55:97:d9:fb:43:6f does not match for "85.62.141.172" (Net::SSH::HostKeyMismatch)
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/verifiers/secure.rb:33:in `verify'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/verifiers/strict.rb:16:in `verify'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/verifiers/lenient.rb:15:in `verify'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:173:in `verify_server_key'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:68:in `exchange_keys'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/algorithms.rb:362:in `exchange_keys'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/algorithms.rb:198:in `proceed!'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/algorithms.rb:146:in `accept_kexinit'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:188:in `loop'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:188:in `poll_message'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:225:in `block in wait'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:223:in `loop'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:223:in `wait'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:88:in `initialize'
    	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:49:in `new'
    	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:49:in `scan_target'
    	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:119:in `block (2 levels) in scan'

**Comment by claudijd** [comment]
We need to either select or create a verifier that will get the keys, but not verify them.

**Comment by jinankjain** [comment]
@claudijd  I added that line in my authorized_keys file but I was able to scan the target normally with no error

**Comment by claudijd** [comment]
@jinankjain try changing the authorized_key entry by a single letter.

**Comment by jinankjain** [comment]
@claudijd I got a connection timeout error

**Comment by claudijd** [comment]
Ok, found a generic way to reproduce this issue...

1.) Find an SSH endpoint that's predictable (a VM of Kali would work)
2.) Go to that SSH endpoint with ssh binary and accept the host key so it's added to your known_hosts files
3.) Go to known hosts file (~/.ssh/known_hosts) and find the entry for that SSH endpoint and replace the public key with another unrelated host key from your known_hosts file
4.) Visit via ssh binary and trigger something like this...

    $ ssh root@192.168.10.99
    key_read: uudecode AAAAB3NzaC1yc2EAAAADAQABAAABAQCjRgKtp9+niK7vEM8oNkYVXjuN8O2YmCdNpBl6UvrhAqbDcf5KpTD6KKN/GfuBpSTcFYwdfxcjaShn2k4UsBRrEvWZLHDevL5kbf2E6VHip0hKHf5PLLoPsjQEd99Is8C5ahxmi3DC1tbcx3cvCZ2D5zkZMK/jRig7Vl+tp/CLP+qvLoGC9NV6w6sswvCeOvTecOKGabpZF8ZtpPbdE2M4rQmNSDy2xXut+Vr3ponr08/uq
     failed
    key_read: uudecode AAAAB3NzaC1yc2EAAAADAQABAAABAQCjRgKtp9+niK7vEM8oNkYVXjuN8O2YmCdNpBl6UvrhAqbDcf5KpTD6KKN/GfuBpSTcFYwdfxcjaShn2k4UsBRrEvWZLHDevL5kbf2E6VHip0hKHf5PLLoPsjQEd99Is8C5ahxmi3DC1tbcx3cvCZ2D5zkZMK/jRig7Vl+tp/CLP+qvLoGC9NV6w6sswvCeOvTecOKGabpZF8ZtpPbdE2M4rQmNSDy2xXut+Vr3ponr08/uq
     failed
    The authenticity of host '192.168.10.99 (192.168.10.99)' can't be established.
    RSA key fingerprint is ad:82:14:b9:81:9e:cf:bd:fd:d2:a1:df:b6:75:86:ce.
    Are you sure you want to continue connecting (yes/no)? no
    Host key verification failed.

5.) Now, scan with ssh_scan and get this...

    $ ./bin/ssh_scan -t 192.168.10.99
    I, [2016-09-18T19:30:10.195200 #12462]  INFO -- : Started ssh_scan of 192.168.10.99
    /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/verifiers/secure.rb:48:in `process_cache_miss': fingerprint ad:82:14:b9:81:9e:cf:bd:fd:d2:a1:df:b6:75:86:ce does not match for "192.168.10.99" (Net::SSH::HostKeyMismatch)
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/verifiers/secure.rb:33:in `verify'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/verifiers/strict.rb:16:in `verify'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/verifiers/lenient.rb:15:in `verify'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:173:in `verify_server_key'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:68:in `exchange_keys'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/algorithms.rb:362:in `exchange_keys'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/algorithms.rb:198:in `proceed!'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/algorithms.rb:146:in `accept_kexinit'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:188:in `loop'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:188:in `poll_message'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:225:in `block in wait'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:223:in `loop'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:223:in `wait'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-4.0.0.beta3/lib/net/ssh/transport/session.rb:88:in `initialize'
    	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:49:in `new'
    	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:49:in `scan_target'
    	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:119:in `block (2 levels) in scan'

**Comment by claudijd** [comment]
The following modification seems to fix this right up...

    $ git diff
    diff --git a/lib/ssh_scan/scan_engine.rb b/lib/ssh_scan/scan_engine.rb
    index 7f68221..3aad9eb 100644
    --- a/lib/ssh_scan/scan_engine.rb
    +++ b/lib/ssh_scan/scan_engine.rb
    @@ -46,7 +46,12 @@ module SSHScan
     
           # Connect and get results (Net-SSH)
           begin
    -        net_ssh_session = Net::SSH::Transport::Session.new(target, :port => port, :timeout => timeout)
    +        net_ssh_session = Net::SSH::Transport::Session.new(
    +                            target,
    +                            :port => port,
    +                            :timeout => timeout,
    +                            :paranoid => Net::SSH::Verifiers::Null.new
    +                          )
             raise SSHScan::Error::ClosedConnection.new if net_ssh_session.closed?
             auth_session = Net::SSH::Authentication::Session.new(net_ssh_session, :auth_methods => ["none"])
             auth_session.authenticate("none", "test", "test")

Sending a PR shortly.
