### ISSUE TITLE
Add output when we detect SSH key re-usage

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#136]
In a case we scan a /24 network and hosts .1 and .2 are using the same host-key, we need some viable way to return in the output that there is key re-usage.

There two two places we might care about this...

1.) During a single /24 scan (maintain off-line state tracking DB -OR- per scan state tracking DB)
2.) During a scan of .2 after we've scanned .1 (maintain off-line state tracking DB?)

**Comment by claudijd** [comment]
Depends on #135 to be completed first.

**Comment by claudijd** [comment]
A fix for #135 is now completed and landed in master.  There are now no blockers on this feature.

**Comment by claudijd** [comment]
Got an attempt on this in https://github.com/mozilla/ssh_scan/pull/194

**Comment by claudijd** [comment]
Fixed in #197

**Comment by royalharsh** [comment]
How much work is left in this? @claudijd
