### ISSUE TITLE
Add SSH version as a policy control

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#154]
Perhaps we want to require that SSH be version 2.0

Maybe this would be a bad example?

 "ssh_version": 1.99,

**Comment by yashmehrotra** [comment]
@claudijd How about adding a minimum SSH version ?

**Comment by claudijd** [comment]
@yashmehrotra minimum SSH version would be fine.  I suspect for default policies the threshold will be 2.0, but I like that it's flexible.
