### ISSUE TITLE
Break fingerprint specs into their own respective files

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#168]
When we have multiple people contributing fingerprints this is aweome, but when we have multiple concurrent adds to the single banner specs file it results in merge conflicts requiring contributors to have to rebase before their add is included.  We want to get rid of this two-step process so people can send us whatever they want and have it stay mergable unless someone is editing the same fingerprint class in which case a conflict makes sense.

**Comment by rishabhs95** [comment]
Yeah, I think it will be much more convenient for contributors as well... will make the specs more modular :)

**Comment by agaurav77** [comment]
@claudijd Should we close this now? Or something else needed?

**Comment by claudijd** [comment]
Nope, it's done, thanks!

**Comment by rishabhs95** [comment]
great work @agaurav77! really liked the new modularised code structure :)
