### ISSUE TITLE
IPv6 fallback bug

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#170]
When a hostname has a AAAA record in DNS and the scanning host has IPv6 IP stack enabled, but the scanning host cannot route IPv6 traffic to the endpoint we end up with an unhandled exception:

    $ ./bin/ssh_scan -t google.com
    I, [2016-09-06T12:48:40.130505 #27225]  INFO -- : Started ssh_scan of google.com:22
    /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/socket.rb:54:in `connect_nonblock': No route to host - connect(2) for [2607:f8b0:4006:80f::200e]:22 (Errno::EHOSTUNREACH)
    	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/socket.rb:54:in `connect_internal'
    	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/socket.rb:140:in `connect'
    	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/socket.rb:338:in `block in tcp'
    	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/socket.rb:232:in `each'
    	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/socket.rb:232:in `foreach'
    	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/socket.rb:328:in `tcp'
    	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/client.rb:21:in `connect'
    	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:23:in `scan_target'
    	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:115:in `block (2 levels) in scan'

Testing was performed with current master (511428f27c6028e8d062f576e7f45f24cd5c4509)

**Comment by claudijd** [comment]
I believe this a bug or a blind spot in the v6/v4 fallback logic.

**Comment by jinankjain** [comment]
I just run the same case and got no error

```
{16-09-06 12:50}[]jinank:~/GitProjects/ssh_scan@master turingmachine% bin/ssh_scan -t google.com
I, [2016-09-06T12:51:28.472788 #9009]  INFO -- : Started ssh_scan of google.com:22
I, [2016-09-06T12:51:30.481573 #9009]  INFO -- : Completed ssh_scan of google.com:22
[
  {
    "ssh_scan_version": "0.0.12",
    "ip": "192.70.222.155",
    "port": "22",
    "error": "ConnectTimeout: Connection timed out - user specified timeout",
    "hostname": "google.com"
  }
]
```

**Comment by jinankjain** [comment]
@claudijd It is again OS dependent error running fine on Linux causing trouble with Mac, I guess it some threading issue which is causing that problem.

**Comment by claudijd** [comment]
It's odd that it would be a threading bug, since the test case is on a single host.  My test case was on a Mac OSX host with IPv6 networking with just a link local address.

**Comment by jinankjain** [comment]
@claudijd There is an error at line 115, that's why I was dubious about the threading bug
