### ISSUE TITLE
Make a gh-page for ssh_scan

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#190]
Description about ssh_scan which includes basic api description and all.
Link to fork or star on github

**Comment by jinankjain** [comment]
@claudijd As a starter I have added a new branch gh-pages where we can develop the gh-page for that and url for that would be: http://mozilla.github.io/ssh_scan/

**Comment by claudijd** [comment]
Cool, thanks!

**Comment by claudijd** [comment]
Source is in gh-pages if anyone wants to take a crack at developing content for it.

**Comment by jinankjain** [comment]
@claudijd Are we planning to use jekyll for gh-page then we need to decide which theme to choose?

**Comment by claudijd** [comment]
Jekyll works for me, feel free to propose a theme, I personally prefer minimal themes

**Comment by jinankjain** [comment]
Some options

- http://themes.jekyllrc.org/phantom/
- http://themes.jekyllrc.org/kasper/

**Comment by claudijd** [comment]
+1 for kasper
