### ISSUE TITLE
ssh_scan/lib/ssh_scan/client.rb:75:in `read': Connection reset by peer (Errno::ECONNRESET)

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#191]
Ran into this bug in a mass ssh_scan...

    /Users/jclaudius/code/ssh_scan/lib/ssh_scan/client.rb:75:in `read': Connection reset by peer (Errno::ECONNRESET)
    	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/client.rb:75:in `get_kex_result'
    	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:42:in `scan_target'
    	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:124:in `block (2 levels) in scan'

**Comment by jinankjain** [comment]
@claudijd We catch this error in client.rb. Then why does it still exists? Kind of surprised

**Comment by claudijd** [comment]
Was on fbe4d36915f425fccdfb0298adf9721babb2f699 when this happened.

**Comment by claudijd** [comment]
@jinankjain we trap this error on #connect but not #get_kex_result, I think that's the nuance here.
