### ISSUE TITLE
Write specs for string_ext

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#200]
We don't have any specs for string_ext, but we depend on it.  This issue is complete when someone adds specs for all the methods in that file.

**Comment by pawandubey** [comment]
I'd like to take this up.

**Comment by claudijd** [comment]
@pawandubey it's all yours 👍

**Comment by claudijd** [comment]
opps... sorry, wrong button

**Comment by flash1452** [comment]
@claudijd I have sent a PR for this issue.
@pawandubey I apologize for intervening but I have been working on this issue for quite some time.

**Comment by pawandubey** [comment]
@flash1452 I'm fine with that. But it's good to let everybody know you're taking something up.

**Comment by flash1452** [comment]
@pawandubey  Yeah I generally do but this time it  just slipped out of my mind.
