### ISSUE TITLE
Add full support for banners identified in #202

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#203]
Add banners from #202

**Comment by agaurav77** [comment]
@claudijd Why don't we maintain a list of the type of banners we support somewhere? Maybe like a todo list, on a wiki page?

**Comment by claudijd** [comment]
@agaurav77 because these types will likely change frequently, I and I'd like to manage them in only one place.

**Comment by claudijd** [comment]
Additionally, there will always be edge cases, so I'd rather have specs for the uniqs

**Comment by claudijd** [comment]
Added more cases in https://github.com/mozilla/ssh_scan/pull/218

Remaining banners to include in our unit-tests include...

"SSH-2.0-mpSSH_0.2.1",
"SSH-2.0-cryptlib",
"SSH-2.0-ServerTech_SSH",
"SSH-2.0-RomSShell_4.62",
"SSH-2.0-PGP",
"SSH-2.0-OpenSSH_7.3",
"SSH-2.0-OpenSSH_7.2",
"SSH-2.0-OpenSSH_7.1",
"SSH-2.0-OpenSSH_6.9",
"SSH-2.0-OpenSSH_6.8p1-hpn14v6",
"SSH-2.0-OpenSSH_6.7",
"SSH-2.0-OpenSSH_6.6p1-hpn14v4",
"SSH-2.0-OpenSSH_6.6.1",
"SSH-2.0-OpenSSH_6.6",
"SSH-2.0-OpenSSH_6.4",
"SSH-2.0-OpenSSH_6.2",
"SSH-2.0-OpenSSH_6.2 FIPS",
"SSH-2.0-OpenSSH_6.1",
"SSH-2.0-OpenSSH_6.0",
"SSH-2.0-OpenSSH_5.9",
"SSH-2.0-OpenSSH_5.8",
"SSH-2.0-OpenSSH_5.6",
"SSH-2.0-OpenSSH_5.4p1 FreeBSD-20100308",
"SSH-2.0-OpenSSH_5.4",
"SSH-2.0-OpenSSH_5.3",
"SSH-2.0-OpenSSH_5.2",
"SSH-2.0-OpenSSH_4.6",
"SSH-2.0-OpenSSH_4.3",
"SSH-2.0-OpenSSH_12.1",
"SSH-2.0-NOS-SSH_2.0",
"SSH-2.0-Mocana SSH ",
"SSH-2.0-IPSSH-6.6.0",
"SSH-2.0-5.32 FlowSsh
"SSH-1.99-OpenSSH_6.7",
"SSH-1.99-OpenSSH_5.3",
"SSH-1.99-OpenSSH_5.0",
"SSH-1.99-OpenSSH_3.7.1p2",

**Comment by claudijd** [comment]
Remaining items...

"SSH-2.0-mpSSH_0.2.1",
"SSH-2.0-cryptlib",
"SSH-2.0-ServerTech_SSH",
"SSH-2.0-RomSShell_4.62",
"SSH-2.0-PGP",
"SSH-2.0-OpenSSH_5.4p1 FreeBSD-20100308",
"SSH-2.0-NOS-SSH_2.0",
"SSH-2.0-Mocana SSH ",
"SSH-2.0-IPSSH-6.6.0",
"SSH-2.0-5.32 FlowSsh",

**Comment by claudijd** [comment]
Remaining items:

"SSH-2.0-mpSSH_0.2.1",
"SSH-2.0-ServerTech_SSH",
"SSH-2.0-PGP",
"SSH-2.0-NOS-SSH_2.0",
"SSH-2.0-Mocana SSH ",
"SSH-2.0-IPSSH-6.6.0",

**Comment by claudijd** [comment]
All of these are now supported as of #229
