### ISSUE TITLE
Make sure Ubuntu CPE reports correctly when the version isn't matched to an OS version

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#205]
Example case was when we saw a banner like this.... "SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-8"

I fixed the fingerprint for this in #204, but to reproduce this bug we just need to see something like "SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-9" and it will improperly show up in the JSON output like this...

    "os_cpe": "o:canonical:ubuntu:#<SSHScan::OS::Ubuntu::Version:0x007f8c9e9741e0>",

**Comment by agaurav77** [comment]
@claudijd Also added a test for the same.
