### ISSUE TITLE
Add a telemetry/heartbeat features

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#207]
Currently, we don't have visibility into whether people are using ssh_scan or not.

It would be nice if there was some very limited data that ssh_scan sent back to a central point to let us know how much use we're actually seeing.

This could be as simple a JSON blob post to a public endpoint that said what version of ssh_scan was in use, a scan was run, how many targets were scanned, whether there were any errors/exceptions, and maybe the SSH banner (to help us improve our fingerprinting).  I would almost even call this a HEARTBEAT feature.

Things we would explicitly not send back would be things like IP scanned, hostname, etc. because we want to respect the privacy of our users.

**Comment by jinankjain** [comment]
Really liked this idea +1

**Comment by claudijd** [comment]
We could use some free IoT data analytics service for this to keep things simple...

**Comment by claudijd** [comment]
This would also be cool because we could take this publicly available data and then resurface it on the soon to be blog or on the readme.  What comes to mind is the number of scans ("How many burgers sold?"), average completed scan size, most common banners, most common exceptions/bug encountered.

**Comment by pawandubey** [comment]
I think if feature were implemented, it would be correct to have a flag to disable it. Or save a setting about it somewhere after the initial run.

**Comment by claudijd** [comment]
@pawandubey yeah, in terms of gem installation, we could have a one-time ask to the end user that basically says "Hey, you willing submit telemetry back to us to make ssh_scan better? (yes/no)" and have the setting be set in the users home dir so it's persistent.  Would probably also be pertinent to add some wiki or blog post that says exactly the attributes we would capture to be transparent.
