### ISSUE TITLE
automate updation of fingerprints

### ISSUE THREAD

**Issue by ashishgaurav13** [mozilla/ssh_scan#209]
I think it would be really cool to keep our fingerprint db updated for different operating systems and ssh libraries. For example, Ubuntu and Dropbear's latest fingerprints can be scraped from their Changelogs. It would be really nice to have a collection of scripts that can be automated to run at specified intervals to update our fingerprints from the sources we have.

Even better, it'd be awesome if these scripts could also update the unit tests. 
Just an idea.

**Comment by claudijd** [comment]
@agaurav77 already has some scripts for this, we can probably land them in a ./scripts folder in their current state so people can see and provide improvements to them.

**Comment by agaurav77** [comment]
@claudijd Added the script for ubuntu. I had the script for dropbear but since we decided to report the version from a single regex, I don't think that can be used anymore.

**Comment by claudijd** [comment]
@agaurav77 sounds good, I landed the ubuntu code.
