### ISSUE TITLE
make gem version checking an opt-out feature

### ISSUE THREAD

**Issue by agaurav77** [mozilla/ssh_scan#211]
We should allow the user to opt out from gem version checking by using a flag like --supress-update-status.

**Comment by claudijd** [comment]
This should also include exception handling for when access to rubygems is not available and we can't determine if an update is available.

**Comment by claudijd** [comment]
See here for more context about the feature https://github.com/mozilla/ssh_scan/pull/210

**Comment by agaurav77** [comment]
Closing, nothing more needed I guess.
