### ISSUE TITLE
Extend ssh fingerprints to include DSA

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#216]
This means namespacing this to DSA and RSA....

    "fingerprints": {
      "dsa": {
        "md5": "9b:82:fe:2f:5d:bb:ac:13:86:10:3a:bb:4c:f2:ba:e5",
        "sha1": "f5:5c:78:f7:47:da:a0:bd:de:65:a2:bb:18:e3:ae:23:81:10:35:71",
        "sha256": "c8:e5:dd:19:0e:84:2b:ff:96:12:9a:e1:bd:66:c9:9e:80:02:69:5e:0d:58:b7:97:2e:d8:96:e5:c1:8d:c9:05"
      }
      "rsa": {
        "md5": "9b:82:fe:2f:5d:bb:ac:13:86:10:3a:bb:4c:f2:ba:e5",
        "sha1": "f5:5c:78:f7:47:da:a0:bd:de:65:a2:bb:18:e3:ae:23:81:10:35:71",
        "sha256": "c8:e5:dd:19:0e:84:2b:ff:96:12:9a:e1:bd:66:c9:9e:80:02:69:5e:0d:58:b7:97:2e:d8:96:e5:c1:8d:c9:05"
      }
    },

And extending the fingerprint DB to support this too, which might require a new row in the fingerprint DB to track key type as well as output modifications to keep the key types separate.

**Comment by claudijd** [comment]
Nice job @royalharsh

**Comment by royalharsh** [comment]
Thanks
