### ISSUE TITLE
Mixed content bug on the blog

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#224]
When I visit the blog via https://mozilla.github.io/ssh_scan/ I'm getting mixed content warnings in Firefox.  I would suggest making the https the preferred scheme if we need to pick one.

/cc @jinankjain

**Comment by claudijd** [comment]
I've also noticed some CSS bugs too, that make loading look a bit weird on http/https

**Comment by jinankjain** [comment]
@claudijd What sort of CSS bugs you are referring to?

**Comment by agaurav77** [comment]
@claudijd @jinankjain I think making site.url to https should fix the issue.

**Comment by jinankjain** [comment]
@agaurav77 I fixed that issue last night 👍

**Comment by claudijd** [comment]
I think whatever you fixed, might have also fixed the CSS issues, I think this is resolved

**Comment by agaurav77** [comment]
Cool, no worries
