### ISSUE TITLE
Follow up API improvements

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#233]
- Add sane security headers to API (to make httpobs happy)
  - https://wiki.mozilla.org/Security/Guidelines/Web_Security
  - Secureheaders is a good starting point (https://github.com/twitter/secureheaders)
- Sync up API with API docs (host vs. target issue)
- Add custom handler for 404s (Ref: http://stackoverflow.com/questions/19781051/rendering-404-in-sinatra-if-file-not-found) and make 404 reference API documentation
- Support self-signed certs (it's not ideal, but it's better and starts to lay framework for SSL/TLS expectations by default)
- Add custom server header
- Add contribute.json
- Add Robots.txt

**Comment by claudijd** [comment]
#234 addresses custom 404 handler and starts using Twitter's secure_headers gem to give us full control over all the security headers we'd want to set.  I just did in enough there to get it functional, but the secure header config should be reworked.

**Comment by claudijd** [comment]
custom server header and moar sane security header settings added to #234

**Comment by agaurav77** [comment]
Changed the wiki, so that's done.

**Comment by claudijd** [comment]
@agaurav77 no SSL at all at this point, would be nice to support at least self-signed ssl vs http as the API default and then provide a path for letsencrypt support.

**Comment by claudijd** [comment]
This has been resolved.
