### ISSUE TITLE
Add something to enforce commit signing on ssh_scan

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#236]
Idea Reference: https://github.com/escapewindow/cot-gpg-keys/blob/master/check_commit_signatures.py

**Comment by agaurav77** [comment]
Even if we have code that can check whether the latest commit is signed or not, where do we add it? 

Do we add a test, say which ensures that each time a travis build is done, the commit must be signed? If we go this way, this would mean that any contributor who does not have signed the last commit cannot do a PR, since the travis build would fail.

Good idea though. I am willing to do this in Ruby if I know where to add the check.

**Comment by claudijd** [comment]
We could just restrict the checks to master, so if there is an unsigned head on master than the master will begin to fail after merge.  This would alert us that something bad has happened.

**Comment by royalharsh** [comment]
How about using bot accounts ? Bots would check if commits have been signed or not and then add labels accordingly, this would allow us to keep a check if commits have been signed or not before merging. One example of such bot : [clabot](https://clabot.github.io/)

**Comment by claudijd** [comment]
@royalharsh this seems cool, I was hoping to have something that could be integrated into the PR logic so it makes it clear whether all commits in the chain are signed.  GitHub already makes this clear with the verified labels, but I'd like something to enforce it for anything that lands in master.  I suppose this could make it harder for landing code by mergers, but I'd like to at least explore the options so we can show others it's possible and use ssh_scan as a reference architecture for it.

**Comment by claudijd** [comment]
#242 is now in production, and seems to have worked

https://travis-ci.org/mozilla/ssh_scan/jobs/169247977

I'll be sending a PR test shortly that is not signed and we'll see how it works.

**Comment by claudijd** [comment]
unsigned commit test here => https://github.com/mozilla/ssh_scan/pull/244

**Comment by agaurav77** [comment]
I think I should change
```
git log --no-merges --format='%H:%GG'
```
to
```
git log --no-merges --format='%H:%GG' master
```

The current enforcing logic always checks the current branch, and we want to fail when master seems fishy.

**Comment by claudijd** [comment]
it did not seem to fail here: https://travis-ci.org/mozilla/ssh_scan/jobs/169346670

**Comment by agaurav77** [comment]
I fixed a few things again. 

Since the last commit is unsigned (just to test), the next commit should fail on Travis.

**Comment by agaurav77** [comment]
The next commit will be see the latest master as signed. So, Travis should not fail.

**Comment by agaurav77** [comment]
This is really weird. Even though the last commit was signed, Travis complains that it is not signed.

https://travis-ci.org/mozilla/ssh_scan/jobs/169381649

```
./spec/ssh_scan/enforce_signed_commits.rb:35:in `<main>': Latest commit 594e80803e5a0b7f0c8a98351bb70217f06f0287 is not signed! (RuntimeError)
```

whereas on my system, it shows

```
594e80803e5a0b7f0c8a98351bb70217f06f0287 is signed by 3F5C4C1BB282EF34(agaurav77)
```

Any ideas?

**Comment by claudijd** [comment]
I honestly don't have enough context here to help, I think in the short-term, maybe we should back out this check and go back to the PR stage.  At that point, maybe I can do some debugging locally using your PR as a test case and see if we can get to the bottom of it.  Today is a little busy for me, so I can probably help out more on Monday.

**Comment by agaurav77** [comment]
@claudijd Any success? Just curious.

**Comment by claudijd** [comment]
I ended up backing this out again, it's just a little too cumbersome to work with and IMO it's a nice to have.   I left the logic there, but just disabled in the travis CI.

**Comment by claudijd** [comment]
This is offered by GitHub now and it's enabled on this repo going forward.
