### ISSUE TITLE
Add a heartbeat route to the api

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#238]
Something like this would be cool to add...

https://github.com/mozilla/tls-observatory/commit/76b73172683d24828ee38fc88dd3e8e04bc8dd16

**Comment by Rajat-Goyal** [comment]
hey @claudijd 
Will it be just that much for a heartbeat route or am i underestimating it ? 
I want to get started off with something simple so let me know if i can take this up. Also if any other input i'll be grateful. :)

**Comment by claudijd** [comment]
@Rajat-Goyal this is actually a really good one to start on.  I'm glad you found it.  It would just be adding something simple here to let us know it's up and running, probably even easier than the reference I linked above...

https://github.com/mozilla/ssh_scan/blob/master/lib/ssh_scan/api.rb#L116-L121

**Comment by claudijd** [comment]
Once you've added the code, you can fire up the api using ./bin/ssh_scan_api and use curl to query the API and see the heartbeat is working.  If you have questions or any hang ups, please ask here and I'll do my best to help you.

**Comment by Rajat-Goyal** [comment]
sure thing i'll start on this :)

**Comment by Rajat-Goyal** [comment]
Added the route and made changes to spec file accordingly. Also ran the rspec test for the file.  I'll be happy if you point out my mistakes as this is my first PR.

**Comment by Rajat-Goyal** [comment]
i need some help. Its failing the travic CI build with the LABEL=docker_build_push. 
I definitely don't understand the travis CI test yet so could you help me with what i am doing wrong ?  i sent a PR before this in which it passed this test but failed another which seems to be working now. Do i need to send a PR for a proper travis CI test ?

**Comment by Rajat-Goyal** [comment]
the travis CI test for docker_build_push is triggered on a PR. I guess that is why it was failing because i tried the travis CI test on my local repository. 
Couldn't we use a similar test to enforce commit signing ?

**Comment by Rajat-Goyal** [comment]
i was going through the discussion on api where marumari suggests that the functions should have the following form 
api/v1/__lbheartbeat__ which returns empty page with 200 and 
api/v1/__heartbeat__ which checks all the dependency returns 500 if not available and 200 if all available 
Really sorry i missed the naming conventions. Just let me know that shall i use __heartbeat__ or __lbheartbeat__ for this route and i'll send a new PR :/

**Comment by claudijd** [comment]
@Rajat-Goyal I don't see any failures relating to your previous comments.  As for the heartbeat code, I've landed it, nice job!

**Comment by claudijd** [comment]
@Rajat-Goyal you may also want to work with @agaurav77 on getting the API documentation updated to reflect the new route so people know it exists.

**Comment by claudijd** [comment]
Documentation link: https://github.com/mozilla/ssh_scan/wiki/ssh_scan-Web-API

**Comment by Rajat-Goyal** [comment]
thanks ! the API documentation is up to date. Is there something more that we would like in the heartbeat route issue or is it done ?

**Comment by claudijd** [comment]
@Rajat-Goyal looks good to me.
