### ISSUE TITLE
Need a mechanism for API authentication

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#262]
Currently, the API prototype has not authentication in place.  As an easy get started way of having authentication in our lives, I'd like to propose a config based token model.

The way it could work is we have a YAML file that sits on disk and it read by the ssh_scan_api.

We would have an authentication section and for each user we would have their api token.

Example:

authentication:
  harsh:
    token: 3206004d-15ea-4bb7-8e35-78e2d4594a54
  claudijd:
    token: af6c8a78-7b84-490a-a540-3f42ea905929

In addition to the configuration file defining the authentication tokens, we would also need to adapt the API routes to enforce those tokens and we would need to update the documentation to reflect which routes require auth and which ones don't.

**Comment by claudijd** [comment]
I'd consider this blocked until we get the basic API end-to-end figured out and implemented.

https://github.com/mozilla/ssh_scan/pull/259

**Comment by jinankjain** [comment]
@claudijd I would suggest go with oauth so that you dont have to go through this token generation phase

**Comment by claudijd** [comment]
@jinankjain sounds fine to me if it's easy to provision users and give them access to things.  If you'd like to prose a strategy, please feel free.

**Comment by claudijd** [comment]
Ideas:

- hawk?
- oauth2?
- gpg?

**Comment by claudijd** [comment]
MWoS meeting discussion considers maybe keeping simple to start

**Comment by kangsterizer** [comment]
Here's the simplest oauth2 example I know of (reference from our conversation during the MWoS meeting):
https://github.com/auth0/nginx-jwt

(yes, I'm also @gdestuynder  ;-)
