### ISSUE TITLE
Missing compliance results in test scan

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#277]
We are missing compliance status on this scan result, indicating a potential bug in SSHScan...  

    $ ./bin/ssh_scan -t 45.55.176.164
    I, [2016-12-02T18:46:03.303035 #10186]  INFO -- : You're using the latest version of ssh_scan 0.0.16
    I, [2016-12-02T18:46:03.307889 #10186]  INFO -- : Started ssh_scan of 45.55.176.164
    I, [2016-12-02T18:46:05.084037 #10186]  INFO -- : Completed ssh_scan of 45.55.176.164
    [
      {
        "ssh_scan_version": "0.0.16",
        "ip": "45.55.176.164",
        "port": 22,
        "server_banner": "SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1",
        "ssh_version": 2.0,
        "os": "ubuntu",
        "os_cpe": "o:canonical:ubuntu:16.04",
        "ssh_lib": "openssh",
        "ssh_lib_cpe": "a:openssh:openssh:7.2p2",
        "cookie": "90c057fc0717b26737576c7dec85d201",
        "key_algorithms": [
          "curve25519-sha256@libssh.org",
          "ecdh-sha2-nistp521",
          "ecdh-sha2-nistp384",
          "ecdh-sha2-nistp256",
          "diffie-hellman-group-exchange-sha256"
        ],
        "server_host_key_algorithms": [
          "ssh-rsa",
          "rsa-sha2-512",
          "rsa-sha2-256",
          "ecdsa-sha2-nistp256",
          "ssh-ed25519"
        ],
        "encryption_algorithms_client_to_server": [
          "chacha20-poly1305@openssh.com",
          "aes256-gcm@openssh.com",
          "aes128-gcm@openssh.com",
          "aes256-ctr",
          "aes192-ctr",
          "aes128-ctr"
        ],
        "encryption_algorithms_server_to_client": [
          "chacha20-poly1305@openssh.com",
          "aes256-gcm@openssh.com",
          "aes128-gcm@openssh.com",
          "aes256-ctr",
          "aes192-ctr",
          "aes128-ctr"
        ],
        "mac_algorithms_client_to_server": [
          "hmac-sha2-512-etm@openssh.com",
          "hmac-sha2-256-etm@openssh.com",
          "umac-128-etm@openssh.com",
          "hmac-sha2-512",
          "hmac-sha2-256",
          "umac-128@openssh.com"
        ],
        "mac_algorithms_server_to_client": [
          "hmac-sha2-512-etm@openssh.com",
          "hmac-sha2-256-etm@openssh.com",
          "umac-128-etm@openssh.com",
          "hmac-sha2-512",
          "hmac-sha2-256",
          "umac-128@openssh.com"
        ],
        "compression_algorithms_client_to_server": [
          "none",
          "zlib@openssh.com"
        ],
        "compression_algorithms_server_to_client": [
          "none",
          "zlib@openssh.com"
        ],
        "languages_client_to_server": [

        ],
        "languages_server_to_client": [

        ],
        "hostname": "",
        "auth_methods": [
          "publickey"
        ],
        "fingerprints": {
          "rsa": {
            "md5": "4f:17:6e:38:63:0c:af:1c:f4:97:4f:ab:04:b4:47:a0",
            "sha1": "8c:71:d0:85:e5:2e:4c:24:34:4b:97:0a:af:37:f4:09:41:8d:ae:6d",
            "sha256": "b5:b1:f8:2f:99:4e:88:bc:9d:6c:81:2b:9f:1c:db:44:2d:dd:e5:66:cb:49:bf:7e:e1:1a:a2:5f:d1:39:d2:16"
          }
        },
        "start_time": "2016-12-02 18:46:03 -0500",
        "end_time": "2016-12-02 18:46:05 -0500",
        "scan_duration_seconds": 1.775981
      }
    ]

**Comment by gerhard-tinned** [comment]
I found the same. Sorry I did see this Ticket too late ... I created a second #280 Ticket for it, sorry.

ssh_scan 0.0.16 (github HEAD) does not show the compliance section but the taged version ssh_scan 0.0.16 (github tags/0.0.16) does contain it in the output.

**Comment by claudijd** [comment]
@gerhard-tinned no worries about the duplicate, I think I fixed the issue while traveling over the weekend, but haven't been back to work until today.  I've pushed #282 to try and resolve this.

**Comment by claudijd** [comment]
Fixed in #282
