### ISSUE TITLE
Port option does not work when specified in the wrong place

### ISSUE THREAD

**Issue by gerhard-tinned** [mozilla/ssh_scan#278]
ssh_scan 0.0.16 (github HEAD)

The -p or --port parameter when specified before the -t or --target option does not have any effect. According to the help screen there is no particular order of the options. Still the options seem to be important. The folloing command tries to access the target via the default port 22. The -p option is ignored.

`ssh_scan  -p 22222 -t 192.168.1.1`

Just replacing the order of the parameters will result in the expected behaviour. The port number to be specified after the target shows that the -p parameter is used. The following command  uses the specified port 22222.

`ssh_scan -t 192.168.1.1 -p 22222`

This behaviour is either a bug or needs to be described in the help screen.

**Comment by claudijd** [comment]
@gerhard-tinned thanks for the report! I'm now working on trying to sort this one out.

I did some initial testing with ssh.mozilla.com, but that is the default port and probably just hiding the bug.

**Comment by claudijd** [comment]
I'll set up a custom port install and test it out.

**Comment by claudijd** [comment]
I was able to confirm this behavior locally...

    claudijd@home ssh_scan (master) $ ./bin/ssh_scan -p 22222 -t 192.168.99.100
    I, [2016-12-05T09:38:19.584176 #14172]  INFO -- : You're using the latest version of ssh_scan 0.0.16
    I, [2016-12-05T09:38:19.585544 #14172]  INFO -- : Started ssh_scan of 192.168.99.100
    I, [2016-12-05T09:38:19.586564 #14172]  INFO -- : Completed ssh_scan of 192.168.99.100
    [
      {
        "ssh_scan_version": "0.0.16",
        "ip": "192.168.99.100",
        "port": 22,
        "error": "ConnectionRefused: Connection refused - connect(2) for 192.168.99.100:22",
        "hostname": ""
      }
    ]
    claudijd@home ssh_scan (master) $ ./bin/ssh_scan -t 192.168.99.100 -p 22222
    I, [2016-12-05T09:38:38.675600 #14176]  INFO -- : You're using the latest version of ssh_scan 0.0.16
    I, [2016-12-05T09:38:38.676539 #14176]  INFO -- : Started ssh_scan of 192.168.99.100:22222
    I, [2016-12-05T09:38:38.756650 #14176]  INFO -- : Completed ssh_scan of 192.168.99.100:22222

**Comment by claudijd** [comment]
@gerhard-tinned I figured out why this is happening, someone added post processing steps in the optparser, but the optparser is read top to bottom, resulting in this issue.  This will require some refactoring that I cannot get to today, but would like to resolve this week.  For the time being, please specify port after target as a workaround until this is fixed.

**Comment by claudijd** [comment]
This has been fixed by #285
