### ISSUE TITLE
The verbosity -V option is not accepted

### ISSUE THREAD

**Issue by gerhard-tinned** [mozilla/ssh_scan#279]
ssh_scan 0.0.16 (github HEAD)

The -V or --verbosity option does not work. Ssh_scan shows the following error message no mather which verbosity level (or non) is set via the command line.

`  ssh_scan -t 192.168.1.1 -p 22222 -V INFO
Can't convert  to any of the Logger level constants
`

It seems the default verbosity level is INFO now.

**Comment by gerhard-tinned** [comment]
Seems as ssh_scan 0.0.16 (github tags/0.0.16) does not honor the -V option as well which breaks the JSON parsing because of the "INFO" messages!!

**Comment by claudijd** [comment]
@gerhard-tinned thanks! I'm looking into this bug now and should have a fix PR proposed today.

**Comment by claudijd** [comment]
In my limited testing, it looks like no logging level is accepted.  I think I might have created this bug with some recent changes in options from symbols to strings on Hash refs, should be resolved shortly.

**Comment by claudijd** [comment]
@gerhard-tinned I think I fixed it.  Please ignore the latest version info, that's another issue I need to fix when running from source.

    $ ./bin/ssh_scan -t ssh.mozilla.com --verbosity DEBUG
    I, [2016-12-05T09:27:49.354186 #14067]  INFO -- : You're using the latest version of ssh_scan 0.0.16
    I, [2016-12-05T09:27:49.355584 #14067]  INFO -- : Started ssh_scan of ssh.mozilla.com
    I, [2016-12-05T09:27:50.786103 #14067]  INFO -- : Completed ssh_scan of ssh.mozilla.com
