### ISSUE TITLE
Add a more detailed schema for SQLite DB entries

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#288]
Currently, we are just storing scan result JSON as a long JSON string in the DB.

To my knowledge, this really doesn't give us a really easy way to run DB queries and extract relevant stats from the DB, which is one of the reasons we're using a DB in the first place.

**Comment by royalharsh** [comment]
I was thinking of using mongodb as our database, as it would make querying the database easier.

**Comment by claudijd** [comment]
@royalharsh sounds fine to me.  I'd like to offer options for database choices and abstract that from the end user using SSHScan::Database namespace and then have the user selection of the DB type result in a different object that SSHScan::Database will use like SSHScan::Database::SQLite or SSHScan::Database::Mongo or SSHScan::Database::Postgres eventually.

**Comment by claudijd** [comment]
I'm closing this, with the expectation that if you want better JSON reporting, then you would use a different DB type that better supports JSON.
