### ISSUE TITLE
Need to update API wiki documentation to reflect newly added routes

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#289]
Documentation: https://github.com/mozilla/ssh_scan/wiki/ssh_scan-Web-API

Examples of what we're missing:

/api/v1/work/results/worker_id/uuid returns the scan with specified worker_id and uuid.
/api/v1/scan/results/delete/worker_id/uuid deletes the scan with specified worked_id and uuid.
/api/v1/scan/results/delete/all deletes all the rows in the table.

**Comment by royalharsh** [comment]
updated the wiki @claudijd
