### ISSUE TITLE
Add IPv6 support/documentation/tests

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#29]
Currently, the tool only supports v4 connections when it should support v4 and v6.

**Comment by mmue** [comment]
As far as I can see the tool already supports IPv6. What am I missing?

```
$ ./bin/ssh_scan -t ip6-localhost
{
  "ssh_scan_version": "0.0.7",
  "hostname": "ip6-localhost",
  "ip": "::1",
  "port": 22,
...
```

```
$ ./bin/ssh_scan -t ::1
{
  "ssh_scan_version": "0.0.7",
  "hostname": "",
  "ip": "::1",
  "port": 22,
...
```

```
$ sudo tcpdump -i lo port ssh
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 65535 bytes
03:14:31.851111 IP6 ip6-localhost.57947 > ip6-localhost.ssh: Flags [S], seq 2346972224, win 43690, options [mss 65476,sackOK,TS val 21290436 ecr 0,nop,wscale 7], length 0
03:14:31.851135 IP6 ip6-localhost.ssh > ip6-localhost.57947: Flags [S.], seq 398082904, ack 2346972225, win 43690, options [mss 65476,sackOK,TS val 21290436 ecr 21290436,nop,wscale 7], length 0
...
```

**Comment by claudijd** [comment]
@mmue ah, thank you for pointing this out.  I only explicitly tested and documented IPv4 support, but as you point out we get v6 sockets for free because it's not explicitly bound to v4.  I suppose since the base v6 functionality is already there then we could focus on the following for this bug...

1.) Build out IPv6 and IPv4 test coverage for this so this is tested and verified during CI runs (I've not done any mocking of v4 of v6 sockets in the specs)
2.) Update the documentation and help to include IPv6 specific help info
3.) Make sure IPv6 DNS hostname resolving is full thought through and if we need a v6 flag in cases where a host is dual-stacked and the DNS hostname has both A and AAAA records available.

This

**Comment by claudijd** [comment]
https://github.com/claudijd/ssh_scan/pull/48 should address point 2 above.

**Comment by jinankjain** [comment]
@claudijd What are things that are pending for this go off the TODO list? I would try to complete that before the new release if you could help me out?

**Comment by claudijd** [comment]
@jinankjain I may have over-thought the scope of this issue since Ruby makes v4/v6 sockets pretty transparent to a developer.  I'm going to close this in favor of #74, which is something I'd like to have coverage for.
