### ISSUE TITLE
Add Github bots for test coverage and dependency vulnerability management

### ISSUE THREAD

**Issue by rishabhs95** [mozilla/ssh_scan#303]
We are thinking to integrate two tools into our project:

- [Hakiri](https://hakiri.io) for monitoring dependency and codebase vulnerabilities 
- [Coveralls](https://coveralls.io) for monitoring test coverage

We think that they may be good for continuously monitoring the changes and suggest immediate improvements with new PRs.

@claudijd  @agaurav77 @royalharsh

**Comment by royalharsh** [comment]
Sounds good. I think it can increase our productivity.

**Comment by claudijd** [comment]
My only hesitation on this is that the Mozilla GitHub org has a large number of projects in it and every time we add a 3rd party integration that requires API tokens and we'll need to engage a GitHub admin for the entire org (I'm merely owner-level on the repo).  If we can do these without needing to engage the admin tier, I'm all for it, but if it's anything more we should discuss during our weekly.

**Comment by rishabhs95** [comment]
So as we discussed earlier, I think we won't be able to integrate much into our repository at the moment. I have some tools like hakiri activated on my fork and so I think that works for now.
So, I'm closing this issue.
