### ISSUE TITLE
Correct rubocop offences?

### ISSUE THREAD

**Issue by rishabhs95** [mozilla/ssh_scan#304]
Currently in our codebase, as we have many contributors, we have non-uniform code-style.
I think we can correct the rubocop offences in our codebase to make the code-style more uniform. I would like this to happen because:

- It will really beautify the code base, i hope (though, it's already beautiful 😬)
- It may be really beneficial for our new future contributors :neckbeard:  
- It will make us more aware about the ruby styling conventions 😄

**Comment by rishabhs95** [comment]
What do you think @claudijd @agaurav77 @royalharsh ?

**Comment by claudijd** [comment]
I think this is a good idea.  I made a big push a couple weeks back to fix a lot of the offenses, but only got partly through the list.  I will also say not all of rubocops exceptions are problems in my view, but for the most part it helped improve the code base.
