### ISSUE TITLE
Provide a generic YAML loader functionality

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#306]
- Should be able to load YAML files as config files
- It support the white-listing of config attributes and error if any config attribute is unexpected

Example of places we could use this, which implement their own loaders.

DB config loader
Policy loader
Worker config loader
API config loader

**Comment by agaurav77** [comment]
So something like a `ConfigLoader` class which would work like
```
allowed_attrs_in_config_file = ["auth_methods", ...]
opts = ConfigLoader.load_config_and_warn(allowed_attrs_in_config_file)
```
Since the list of attributes would be too much sometimes, so lets store all attrs possible in a YAML file at `configs/api.yaml` (say), then
```
opts = ConfigLoader.load_config_and_warn(SSHScan::API)
```
where the class is sufficient to deduce the config file.

@claudijd @royalharsh @rishabhs95 ?

**Comment by claudijd** [comment]
This is done, pending landing.
