### ISSUE TITLE
Add authentication and authentication bypass for workers

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#321]
When we enable authentication right now, all API name-spaced routes require authentication tokens.

This is cool and works well for the end user, but it creates a weird distribution problem for workers, especially a worker is on the same system that really shouldn't need a token.

This is what I'd like to propose:

1. No not require authentication from loopback sources (this includes users and workers and makes local operations/debugging more sane)
2. Implement authentication logic for the ./bin/ssh_scan_worker so that when a worker is setup remotely it knows how to properly authenticate.
3. Add a worker namespace under the authentication config that's separate from users.  Here we can generate tokens for workers and make sure they authenticate for every request they make.

**Comment by agaurav77** [comment]
This will depend on #328.
