### ISSUE TITLE
API authentication is broken

### ISSUE THREAD

**Issue by agaurav77** [mozilla/ssh_scan#328]
Currently, scans are not processed if they are added via an authenticated request. For example, if I add a token `testpass` for user `test`, and do

```bash
$ curl --data "target=192.168.11.22&port=9999" http://localhost:8000/api/v1/scan -H "SSH_SCAN_AUTH_TOKEN: testpass"
{"uuid":"dc90e613-5c20-4de6-b893-44bc86d39b16"}
```

then I get a scan not found error when I try to retrieve the scan:

```bash
$ curl http://localhost:8000/api/v1/scan/results\?uuid\=dc90e613-5c20-4de6-b893-44bc86d39b16 -H "SSH_SCAN_AUTH_TOKEN: testpass"
{"scan":"not found"}
```

**Comment by claudijd** [comment]
It's hard to say if this was fixed in my recent bug fix of the workers or you had it setup incorrectly.

I did spend some time tonight to setup an environment and verify the authentication stuff works against  current master branch (31f118f7d7bd241dd4e6ab5ecee8bc8b51440247) with some test tokens.  Here's the config I used...

		$ git diff
		diff --git a/config/api/config.yml b/config/api/config.yml
		index 1db633b..fc9aa2b 100644
		--- a/config/api/config.yml
		+++ b/config/api/config.yml
		@@ -7,7 +7,7 @@ port: 8000
		 # API Tokens (a crude mechanism for adding auth to your API)
		 #authentication: true
		-authentication: false
		+authentication: true
		 # If authentication is to true, the authentication tokens you generate below
		 # will be required to access certain API functions.
		@@ -15,17 +15,17 @@ authentication: false
		 # Generate a new token using Ruby's Secure random uuid
		 # $ ruby -r securerandom -e 'puts SecureRandom.uuid'
		 #
		-# users:
		-#   - username    : starlord
		-#     token       : INSERT_GROOT_TOKEN
		+users:
		+  - username    : starlord
		+    token       : c7b5a761-71a8-4814-8849-d2208247cf63
		 #   - username    : groot
		 #     token       : INSERT_GROOT_TOKEN
		 #   - username    : gamora
		 #     token       : INSERT_GAMORA_TOKEN
		 
		-# workers:
		-#   - worker_name : worker1
		-#     token       : INSERT_WORKER1_TOKEN
		+workers:
		+  - worker_name : worker1
		+    token       : 2463c915-7c35-48e6-bb79-7a03c6a15f94
		 # Define database configuration
		 # MongoDB Example
		diff --git a/config/worker/config.yml b/config/worker/config.yml
		index 766db01..4c412aa 100644
		--- a/config/worker/config.yml
		+++ b/config/worker/config.yml
		@@ -19,4 +19,4 @@ verify: false
		 # Authentication - if using authentication on the API, you'll 
		 # need to have an auth token with matches in the API configuration
		-# auth_token: INSERT_WORKER_TOKEN
		+auth_token: 2463c915-7c35-48e6-bb79-7a03c6a15f94

Here's my worker output...

		./bin/ssh_scan_worker
		I, [2017-03-01T21:33:39.984744 #28867]  INFO -- : No jobs available (waiting 5 seconds)
		I, [2017-03-01T21:33:44.992409 #28867]  INFO -- : No jobs available (waiting 5 seconds)
		I, [2017-03-01T21:33:49.995498 #28867]  INFO -- : Started job: a80d4554-0b31-4e26-8491-366d3cc1184f
		I, [2017-03-01T21:33:52.133165 #28867]  INFO -- : Completed job: a80d4554-0b31-4e26-8491-366d3cc1184f
		I, [2017-03-01T21:33:52.138351 #28867]  INFO -- : Posted job: a80d4554-0b31-4e26-8491-366d3cc1184f

Here's my api output...

		127.0.0.1 - - [01/Mar/2017:21:33:48 -0500] "POST /api/v1/scan?target=ssh.mozilla.com HTTP/1.1" 200 47 0.0013
		W, [2017-03-01T21:33:49.994122 #28868]  WARN -- : Worker  polls for Job
		W, [2017-03-01T21:33:49.994195 #28868]  WARN -- : Worker  got job a80d4554-0b31-4e26-8491-366d3cc1184f
		127.0.0.1 - - [01/Mar/2017:21:33:49 -0500] "GET /api/v1/work HTTP/1.1" 200 332 0.0015
		127.0.0.1 - - [01/Mar/2017:21:33:52 -0500] "POST /api/v1/work/results/6cb6707f-7e25-43ba-8fa2-c22ed34b846e/a80d4554-0b31-4e26-8491-366d3cc1184f HTTP/1.1" 200 - 0.0039
		W, [2017-03-01T21:33:52.139259 #28868]  WARN -- : Worker  polls for Job
		W, [2017-03-01T21:33:52.139333 #28868]  WARN -- : Worker  didn't get any work
		127.0.0.1 - - [01/Mar/2017:21:33:52 -0500] "GET /api/v1/work HTTP/1.1" 200 14 0.0008
		W, [2017-03-01T21:33:57.142139 #28868]  WARN -- : Worker  polls for Job
		W, [2017-03-01T21:33:57.142180 #28868]  WARN -- : Worker  didn't get any work
		127.0.0.1 - - [01/Mar/2017:21:33:57 -0500] "GET /api/v1/work HTTP/1.1" 200 14 0.0010
		W, [2017-03-01T21:34:02.149720 #28868]  WARN -- : Worker  polls for Job
		W, [2017-03-01T21:34:02.149793 #28868]  WARN -- : Worker  didn't get any work
		127.0.0.1 - - [01/Mar/2017:21:34:02 -0500] "GET /api/v1/work HTTP/1.1" 200 14 0.0017
		W, [2017-03-01T21:34:07.152710 #28868]  WARN -- : Worker  polls for Job
		W, [2017-03-01T21:34:07.152755 #28868]  WARN -- : Worker  didn't get any work
		127.0.0.1 - - [01/Mar/2017:21:34:07 -0500] "GET /api/v1/work HTTP/1.1" 200 14 0.0010
		127.0.0.1 - - [01/Mar/2017:21:34:08 -0500] "GET /api/v1/scan/results?uuid=a80d4554-0b31-4e26-8491-366d3cc1184f HTTP/1.1" 200 36 0.0009

And here's my client curl output...

		$ curl -k -H "SSH_SCAN_AUTH_TOKEN: c7b5a761-71a8-4814-8849-d2208247cf63" -X POST http://127.0.0.1:8000/api/v1/scan?target=ssh.mozilla.com
		{"uuid":"a80d4554-0b31-4e26-8491-366d3cc1184f"}
        $ curl -k -H "SSH_SCAN_AUTH_TOKEN: c7b5a761-71a8-4814-8849-d2208247cf63" http://127.0.0.1:8000/api/v1/scan/results?uuid=a80d4554-0b31-4e26-8491-366d3cc1184f
		{"ssh_scan_version":"0.0.16","ip":"63.245.214.149","port":"22","server_banner":"SSH-2.0-OpenSSH_6.6.1","ssh_version":2.0,"os":"unknown","os_cpe":"o:unknown","ssh_lib":"openssh","ssh_lib_cpe":"a:openssh:openssh:6.6.1","cookie":"42a48c99db1b4398349aea5f3407e2ea","key_algorithms":["curve25519-sha256@libssh.org","ecdh-sha2-nistp256","ecdh-sha2-nistp384","ecdh-sha2-nistp521","diffie-hellman-group-exchange-sha256","diffie-hellman-group-exchange-sha1","diffie-hellman-group14-sha1","diffie-hellman-group1-sha1"],"server_host_key_algorithms":["ssh-rsa","ecdsa-sha2-nistp256","ssh-ed25519"],"encryption_algorithms_client_to_server":["aes128-ctr","aes192-ctr","aes256-ctr","arcfour256","arcfour128","aes128-gcm@openssh.com","aes256-gcm@openssh.com","chacha20-poly1305@openssh.com","aes128-cbc","3des-cbc","blowfish-cbc","cast128-cbc","aes192-cbc","aes256-cbc","arcfour","rijndael-cbc@lysator.liu.se"],"encryption_algorithms_server_to_client":["aes128-ctr","aes192-ctr","aes256-ctr","arcfour256","arcfour128","aes128-gcm@openssh.com","aes256-gcm@openssh.com","chacha20-poly1305@openssh.com","aes128-cbc","3des-cbc","blowfish-cbc","cast128-cbc","aes192-cbc","aes256-cbc","arcfour","rijndael-cbc@lysator.liu.se"],"mac_algorithms_client_to_server":["hmac-md5-etm@openssh.com","hmac-sha1-etm@openssh.com","umac-64-etm@openssh.com","umac-128-etm@openssh.com","hmac-sha2-256-etm@openssh.com","hmac-sha2-512-etm@openssh.com","hmac-ripemd160-etm@openssh.com","hmac-sha1-96-etm@openssh.com","hmac-md5-96-etm@openssh.com","hmac-md5","hmac-sha1","umac-64@openssh.com","umac-128@openssh.com","hmac-sha2-256","hmac-sha2-512","hmac-ripemd160","hmac-ripemd160@openssh.com","hmac-sha1-96","hmac-md5-96"],"mac_algorithms_server_to_client":["hmac-md5-etm@openssh.com","hmac-sha1-etm@openssh.com","umac-64-etm@openssh.com","umac-128-etm@openssh.com","hmac-sha2-256-etm@openssh.com","hmac-sha2-512-etm@openssh.com","hmac-ripemd160-etm@openssh.com","hmac-sha1-96-etm@openssh.com","hmac-md5-96-etm@openssh.com","hmac-md5","hmac-sha1","umac-64@openssh.com","umac-128@openssh.com","hmac-sha2-256","hmac-sha2-512","hmac-ripemd160","hmac-ripemd160@openssh.com","hmac-sha1-96","hmac-md5-96"],"compression_algorithms_client_to_server":["none","zlib@openssh.com"],"compression_algorithms_server_to_client":["none","zlib@openssh.com"],"languages_client_to_server":[],"languages_server_to_client":[],"hostname":"ssh.mozilla.com","auth_methods":["publickey"],"fingerprints":{"rsa":{"md5":"17:97:3a:64:83:4e:4f:fd:5d:d1:f5:fc:d5:9a:fb:15","sha1":"01:89:8a:f1:07:52:47:54:a5:58:99:77:23:0b:63:a5:d8:07:80:12","sha256":"23:4e:2e:30:8e:bd:bb:ae:65:55:57:a9:df:70:8c:c6:ac:48:18:f7:a0:3b:1e:ba:aa:c2:f4:d4:e6:f4:4b:6a"}},"start_time":"2017-03-01 21:33:49 -0500","end_time":"2017-03-01 21:33:52 -0500","scan_duration_seconds":2.13652,"compliance":{"policy":"Mozilla Modern","compliant":false,"recommendations":["Remove these Key Exchange Algos: diffie-hellman-group-exchange-sha1, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1","Remove these MAC Algos: hmac-md5-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64-etm@openssh.com, hmac-ripemd160-etm@openssh.com, hmac-sha1-96-etm@openssh.com, hmac-md5-96-etm@openssh.com, hmac-md5, hmac-sha1, umac-64@openssh.com, hmac-ripemd160, hmac-ripemd160@openssh.com, hmac-sha1-96, hmac-md5-96","Remove these Encryption Ciphers: arcfour256, arcfour128, aes128-cbc, 3des-cbc, blowfish-cbc, cast128-cbc, aes192-cbc, aes256-cbc, arcfour, rijndael-cbc@lysator.liu.se"],"references":["https://wiki.mozilla.org/Security/Guidelines/OpenSSH"]}}

**Comment by claudijd** [comment]
@agaurav77 because of the above testing, I think this issue is resolved.  Please have a look again and let me know if this issue is resolved to your satisfaction.
