### ISSUE TITLE
ssh_scan for acceptance testing (Serverspec integration?)

### ISSUE THREAD

**Issue by petems** [mozilla/ssh_scan#353]
So as mentioned in #347 here's some context to what I'm doing with `ssh_scan`:

I'm writing a module to harden SSH servers according to the SSH guidelines: https://github.com/petems/petems-mozilla_ssh_hardening

So the module configures a server, sets up the SSH config as the instructions say, then uses a combination of [beaker](https://github.com/puppetlabs/beaker)(Puppet's acceptance testing framework) and [serverspec](http://serverspec.org/) to actually check it's running correctly (port 22 open, config file in place etc)

I've extended it recently to actually run `ssh_scan` against the instance of SSH being configured.

Code looks like this:

```ruby
describe command("/opt/puppetlabs/puppet/bin/gem install ssh_scan -v 0.0.18") do
  its(:exit_status) { should eq 0 }
  its(:stdout) { should match /Successfully installed ssh_scan/ }
end
describe command("/opt/puppetlabs/puppet/bin/ssh_scan -u -t #{fact('ipaddress')} 2>&1") do
  its(:exit_status) { should eq 0 }
  its(:stdout) { should match /"ssh_scan_version": "0.0.18"/ }
end
```

So essentially I can explicitly check my requirements: that the Puppet code I'm writing creates a machine that passes an `ssh_scan` run. 

Pretty cool huh?

What I'd really like is the ability for ssh_scan to be an API I can access, then have it as a dedicated serverspec resource that I can call:

```ruby
describe ssh do
  it { should have_cipher('aes256-ctr') }
  it { should have_mac('hmac-sha2-512-etm') }
  it { should have_kex('curve25519-sha256') }
end
```

**Comment by claudijd** [comment]
@petems wow, that's really cool!  Thanks for sharing!

**Comment by petems** [comment]
@claudijd I can see that some parts of ssh_scan are being remodeled for the server workflow, I might see if I can implement this as a serverspec resource if I have some time 😄

**Comment by claudijd** [comment]
@petems yeah, we had an MWoS student project team that created a more scalable infra for it, in case we ever decide to integrated with Mozilla Observatory.  I recently separated those projects into engine and API to ensure their gem deps didn't get too crazy.

**Comment by claudijd** [comment]
let me know if you have any questions as you go along or need bug fixes prioritized.

**Comment by claudijd** [comment]
@petems just checking in to see how you made out with this?

**Comment by petems** [comment]
The work to turn it into an inspec module was pretty heavy, and I dont really work in a config management space much anymore so not working on it.

If someone else wants to pick up the regins they are welcome to do so! 😄

**Comment by claudijd** [comment]
@petems sorry to hear that, hope all is well!

**Comment by petems** [comment]
No worries, it was a happy switch, I'm over at HashiCorp now, so if there's some way of integrating this with the Hashi stack stuff I might pick it up 😄
