### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ImNtReal** [mozilla/ssh_scan#358]
What license is this released under?

**Comment by claudijd** [comment]
@ImNtReal yeah, I guess I never added a license, any preference before I slap on there?

**Comment by ImNtReal** [comment]
Not really. I was guessing MPL since it's a Mozilla project, or MIT since it's the GitHub default. Then I noticed a lot of Ruby projects using Apache. Any of those work for me.

**Comment by claudijd** [comment]
@ImNtReal all fixed up, thanks again for the report!
