### ISSUE TITLE
Add negotiated ciphers

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#375]
Sort of like with ssl testing, what ssh ciphers were actuall negotiated successfully?

We'd need to extract this from the net-ssh traffic, but is totally doable.

**Comment by april** [comment]
We already have the ciphers available to both sides.  In this case, I simply want to know what cipher suite would have been used had an actual session been negotiated.

**Comment by claudijd** [comment]
If I recall the spec assumption is first mutual match top down, so this is pretty trivial to add/mock up.

I also want to make the results container a real class, rather than a loosely coupled Hash that is the source of a lot of buggies.  Maybe I can add those in the same breadth, when the Result object is a full-blown class.

**Comment by claudijd** [comment]
Created buggie for results promotion to first-class citizen class => https://github.com/mozilla/ssh_scan/issues/377

**Comment by claudijd** [comment]
This may actually prove more difficult than originally thought.

Looks like when we scan, it's based on explicit parameters that are set in SSH scan.

This would mean that our key init for the client would need to be exhaustive to ensure an accurate negotiated cipher deduction.

**Comment by april** [comment]
Isn't it already pretty exhaustive?  I get all the ciphers available in both directions?

**Comment by claudijd** [comment]
This is what we're proposing initially...

https://github.com/mozilla/ssh_scan/blob/master/lib/ssh_scan/constants.rb#L11-L34

It's definately a subset of what openssh supports.  relatively easy to ammend, but I haven't tested whether server replies are even dependent on client proposals.  I would expect that such research would need to be done as a prereq here.
