### ISSUE TITLE
client ssh_config

### ISSUE THREAD

**Issue by jammasterj89** [mozilla/ssh_scan#385]
Correct me if I'm wrong but this scans the sshd_config on the server you are trying to connect to. Is there a way to use this tool to scan the client (ssh_config) as well?

**Comment by claudijd** [comment]
Technically, ssh_scan doesn't look at the config files at all, it merely looks at what the server offers in it's kex response packet.

I suppose there are a couple ways at validating client configs, which would include

1.) looking at the ssh_config itself (this is probably best managed by a config mgmt tool, like puppet)
2.) or potentially making an SSH type server service that does nothing that capture what the client's initial kex initial request would be.

As for how this relates to ssh_scan, it currently does not have any local config scanning capability (initial focus is really about actual servers).  I'm however open to the idea of extending it support config file reading, but note that it's actually pretty hard to do that unless you know the openssh version in use and it's defaults (in cases where specific parameters are not supplied it falls back to that version of openssh defaults).  This means that the config itself isn't all that useful unless all the parameters are explicitly supplied.

I realize that's sort of a long winded response, but let me know if you think that makes sense of have interest in writing an extension for config file scanning.  I'm sure there are some ways of being able to provide guidance even with in a partially incomplete picture.

**Comment by jammasterj89** [comment]
Hi @claudijd, thank you for the reply! I'd be interested in writing an extension in the future, I would just need to brush up on my Ruby first. I don't need to test this immediately or anything it was more just curiosity whether the tool currently supports the client, but your response makes perfect sense. But it might be worth configuring the client (I'm using chef) so might have a quick look around that first. Thanks again.
