### ISSUE TITLE
Stack trace Errno::ECONNRESET

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#392]
```
 $ ruby bin/ssh_scan -t 68.245.18.44
/Users/jclaudius/code/ssh_scan/lib/ssh_scan/client.rb:69:in `gets': Connection reset by peer @ io_fillbuf - fd:7  (Errno::ECONNRESET)
	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/client.rb:69:in `connect'
	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:73:in `scan_target'
	from /Users/jclaudius/code/ssh_scan/lib/ssh_scan/scan_engine.rb:176:in `block (2 levels) in scan'
```

**Comment by claudijd** [comment]
Expected fix is just moving the banner grab into the above begin block here:

https://github.com/mozilla/ssh_scan/blob/master/lib/ssh_scan/client.rb#L69

**Comment by claudijd** [comment]
FWIW, this is not a real SSH endpoint

**Comment by floatingatoll** [comment]
(Elided the real IP out of the original issue text.)

**Comment by claudijd** [comment]
Thanks, I generally include the original target because I often cannot fix bugs at the time of finding them and need to record them for a later point.  But I appreciate the diligence here!

**Comment by floatingatoll** [comment]
Yeah, I figured once you'd fixed it, the Internet didn't need a free IP to
scan :)
