### ISSUE TITLE
Multiport support

### ISSUE THREAD

**Issue by danmx** [mozilla/ssh_scan#411]
It would be useful to launch a single scan for multiple ports like it can be done using nmap with NSE scripts.

**Comment by jinankjain** [comment]
It does support multi port scanning. You can pass multiple ports comma separated, I assume.

**Comment by claudijd** [comment]
Yes, I believe @jinankjain is right.  Also, to be clear, ssh_scan is not intended as a port scanning tool per say.  The expectation is that you already know where you have ssh services listening.  It will handle cases where a service is not there by timing out, but you should have no expectation of that being performant.
