### ISSUE TITLE
lib/ssh_scan/result.rb:26:in `ip=': Invalid attempt to set IP to a non-IP address value (ArgumentError)

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#412]
Noticed this error in prod SSH OBs, need to figure out why we're getting here...

`
/usr/local/bundle/gems/ssh_scan-0.0.26/lib/ssh_scan/result.rb:26:in `ip=': Invalid attempt to set IP to a non-IP address value (ArgumentError)
	from /usr/local/bundle/gems/ssh_scan-0.0.26/lib/ssh_scan/result.rb:201:in `set_client_attributes'
	from /usr/local/bundle/gems/ssh_scan-0.0.26/lib/ssh_scan/scan_engine.rb:51:in `scan_target'
	from /usr/local/bundle/gems/ssh_scan-0.0.26/lib/ssh_scan/scan_engine.rb:176:in `block (2 levels) in scan'
`

**Comment by floatingatoll** [comment]
Could this be an IPv6 compat complaint, for an AAAA-only hostname?

**Comment by claudijd** [comment]
It could be, but I do know for sure that even though ssh_scan is IPv6 compat as well at the production instance.  The only thing it's missing right now is fixing this in the docker layer, which I haven't fixed yet.

Full IPv6 end-to-end compat is a source of a few other bugs I'm tracking on, so I think they will die soon as I can get that docker peice fixed.  I'm also landing a bunch of other bug fixes today too, so it's possible I'll pick this off in one of those efforts.

**Comment by claudijd** [comment]
Repro with this when ready to fix: bpi.mosos.de (using ssh_client on 0.0.27)

**Comment by claudijd** [comment]
And yes, definitely an IPv6 issue

**Comment by claudijd** [comment]
#472
