### ISSUE TITLE
Build a fingerprinting prototype of ssh_scan that makes use of rapid7/recog

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#416]
Just so this is not lost into the ether...

https://github.com/rapid7/recog

/cc @tsellers-r7

**Comment by claudijd** [comment]
@tsellers-r7, would you mind sharing any open-source bits on how you think would be the best way to shim this in?  I will find the bits in ssh_scan where this is implemented and share links in further comments.

**Comment by claudijd** [comment]
This is where some of the magic happens, I suspect we can probably just expose an alternative method to start with that just makes a call to recog and retrieves whatever we know and then we can compare the two against a series of example cases and see if there's a significant value add.   Happy to write most of the code, but having a "this is the best way to call recog" info would speed it up.

**Comment by tsellers-r7** [comment]
@claudijd Sorry, I've been a bit tied up.  I'll try to provide something useful in the next couple of days.

**Comment by claudijd** [comment]
Bailing on this.

**Comment by claudijd** [comment]
If you would like it reopened, we can totally do that.

**Comment by tsellers-r7** [comment]
Thanks. I'll see what I can do to either set aside time for this or let you know that I can't.

**Comment by claudijd** [comment]
@tsellers-r7 all good.  Good to hear from you!
