### ISSUE TITLE
uninitialized constant Net::SSH::Verifiers::Null

### ISSUE THREAD

**Issue by exploide** [mozilla/ssh_scan#435]
I just installed ssh_scan but when I try to run it to scan a host, the following error occurs.

```
#<Thread:0x000055b6c39ee060@/home/jvieten/.gem/ruby/gems/ssh_scan-0.0.34/lib/ssh_scan/scan_engine.rb:188 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	1: from /home/jvieten/.gem/ruby/gems/ssh_scan-0.0.34/lib/ssh_scan/scan_engine.rb:191:in `block (2 levels) in scan'
/home/jvieten/.gem/ruby/gems/ssh_scan-0.0.34/lib/ssh_scan/scan_engine.rb:99:in `scan_target': uninitialized constant Net::SSH::Verifiers::Null (NameError)
Traceback (most recent call last):
	1: from /home/jvieten/.gem/ruby/gems/ssh_scan-0.0.34/lib/ssh_scan/scan_engine.rb:191:in `block (2 levels) in scan'
/home/jvieten/.gem/ruby/gems/ssh_scan-0.0.34/lib/ssh_scan/scan_engine.rb:99:in `scan_target': uninitialized constant Net::SSH::Verifiers::Null (NameError)
```

I'm on a Fedora 28 machine with ruby 2.5.1.

**Comment by claudijd** [comment]
@exploide thanks for the report, can you provide what version of Net::SSH you are using?

`gem list | grep net-ssh`

**Comment by claudijd** [comment]
@exploide would you be so kind as you back-rev your net-ssh for the sake of testing?  Say to net-ssh version 4.2.0 and see if that fixes temporarily?

**Comment by claudijd** [comment]
I'm also bumping the CI Rubies to see if I can trigger the issue there as well.

**Comment by claudijd** [comment]
Yes, I was able to trigger this in the CI builds, I think by fixing to 2.4.x net-ssh this should fix it.

**Comment by claudijd** [comment]
tracker issue to dig into 5.x impact can be found at https://github.com/mozilla/ssh_scan/issues/437

**Comment by claudijd** [comment]
It does appear to be the case that if we back-rev the net-ssh to 4.2.x that all CI builds return to normal.  I will issue a point release to address this problem shortly.

**Comment by exploide** [comment]
Awesome. Thank you very much for addressing this so quickly! :)

**Comment by claudijd** [comment]
https://github.com/mozilla/ssh_scan/releases/tag/0.0.35 has been released to fix this problem.  We'll deal with the longer tail of making this net-ssh 5.x compatible in #437.  Again, many thanks for your report!

**Comment by claudijd** [comment]
@exploide please do let me know if 0.0.35 does not fix the issue for you, though I think I got it.

**Comment by claudijd** [comment]
https://github.com/mozilla/ssh_scan/pull/436

**Comment by exploide** [comment]
I also assume this will fix the issue. If I find out tomorrow that it still won't work, I'll let you know. But I really think you fixed it.

BTW, concerning your thoughts mentioned in #437 maybe scheduling a Travis cron job will be a step in the desired direction. https://docs.travis-ci.com/user/cron-jobs/ But I don't know if this requires a special plan or is free to use.

**Comment by claudijd** [comment]
@exploide thanks, I'll check out the cron-job stuff
