### ISSUE TITLE
Review behavior changes of net-ssh 5.x and make adjustments as needed

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#437]
We recently got a report of a behavior change in net-ssh 5.x builds, released a few days ago, this bug is to investigate what changed that prevents NullVerifiers and any other behavior to see what we need to fix up.

I also increased out integration coverage to better detect this, although, I wish it would just run daily and let me know when/if it breaks.  That or publishing a gemfile.lock in the repo and periodically revisiting to bump deps and update.  Though, I'm a fan of living on the edge and dealing with small bumps rather than delayed big bumps with multiple thigns to fix.

**Comment by fmjgomes** [comment]
Fix: 
go to file **ssh_scan.gemspec** and change on line 35 the net-ssh version to '5.0.2' go ahead and save it

next go to lib/ssh_scan/ and edit scan_engine.rb  on line 99 and change the line to **:paranoid => false** 

you may need to go back a couple of folders to the ssh_scan root and run: **gem build ssh_scan.gemspec**

**Comment by claudijd** [comment]
@fmjgomes I made a PR for these changes, please have a look if you can for review (https://github.com/mozilla/ssh_scan/pull/441)
