### ISSUE TITLE
Add support for SSHv1

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#47]
Currently, ssh_scan only supports SSHv2 (the most common/modern version of SSH).  Old devices like Cisco routers for example also support SSHv1, which is a slightly different protocol that we'd need to implement and support.

**Comment by jinankjain** [comment]
Now as we are planning to use net-ssh they have support for SSH v1 also so we won't be needing this

**Comment by claudijd** [comment]
I would like to leave this bug open until we have have fully removed the SSHv2 expectations in https://github.com/mozilla/ssh_scan/blob/master/lib/ssh_scan/client.rb  Basically, I would like to leave the interfaces of the client the same, but have it use Net::SSH under the hood.

**Comment by claudijd** [comment]
But, I agreed, eventually this can be removed.  I seem to remember v1 support in net-ssh to be spotty, but we can cross that bridge when/if we get there.

**Comment by claudijd** [comment]
I looked into a drop in replacement for net-ssh in the client and it turns out we might need to monkey patch a bunch of net-ssh to get access to it's internals and access all the data element in the kex_init exchange.  I'm thinking it might be worthwhile to eventually develop a protocol fingerprinting tier first that simply detects SSH that might use the native protcol in SSHScan and then once we're sure it's somehting we can talk to and can enumerate it's attributes then we can commit to connecting with net-ssh.

**Comment by jinankjain** [comment]
@claudijd I think we should now start doing that monkey patch for net-ssh so that we can support ssh v1

**Comment by claudijd** [comment]
@jinankjain we actually have two options here:

1.) Monkey patch net-ssh objects to give us direct access to their internals
-OR-
2.) Simply implement the kex-init data structure equivalent in SSHv1 (if it even exists).

I personally prefer leaning toward option #2 because it gives us more control over that initial point when we start talking to the end point and have a lot more flexibility and exception control without binding ourselves to a specific net-ssh version, which is likely to vary from Ruby version to Ruby version (we should expect a certain amount of variability here in the currently supported Rubies)

**Comment by jinankjain** [comment]
@claudijd I will go by RFC for ssh v1 and try to look what are the key exchange rules written there and implement those over this week.

**Comment by claudijd** [comment]
@jinankjain sounds good, thanks!

**Comment by jinankjain** [comment]
@claudijd I looked for RFC for ssh v1 they don't have much documentation for that so I think monkey patching with net-ssh would be a good idea

**Comment by claudijd** [comment]
@jinankjain the protocol specification should be pretty straight forward, if not, we could just capture an SSHv1 init and reverse it from wireshark.

**Comment by jinankjain** [comment]
@claudijd On my machine I have ssh v2 configured so I cannot do a packet capture for ssh v1

**Comment by claudijd** [comment]
v1 tech is pretty old, I'd rather not chase this with the little resources we have
