### ISSUE TITLE
no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by exploide** [mozilla/ssh_scan#477]
Since the upgrade to 0.0.37, I get the following error when running `ssh_scan -t mytarget`:

```
#<Thread:0x00007f84e41cd930@~/.gem/gems/ssh_scan-0.0.37/lib/ssh_scan/subprocess.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	2: from ~/.gem/gems/ssh_scan-0.0.37/lib/ssh_scan/subprocess.rb:16:in `block (3 levels) in initialize'
	1: from ~/.gem/gems/ssh_scan-0.0.37/lib/ssh_scan/scan_engine.rb:129:in `block in scan_target'
~/.gem/gems/ssh_scan-0.0.37/lib/ssh_scan/scan_engine.rb:129:in `+': no implicit conversion of nil into String (TypeError)
```

However, the scan is performed regularly and I can see the result right after the error.

**Comment by Allaman** [comment]
I can confirm the same message in the docker image `mozilla/ssh_scan` as well

**Comment by claudijd** [comment]
Thanks for the bug report, can you please provide a public example so I can repro and fix ASAP?

**Comment by claudijd** [comment]
This is the type of repro I'm looking for, if you can do it...

 (master) $ ssh_scan --version
0.0.37
 (master) $ ssh_scan -t ssh.mozilla.com
[
  {
    "ssh_scan_version": "0.0.37",
    "ip": "63.245.208.111",
    "hostname": "ssh.mozilla.com",
    "port": 22,
    "server_banner": "SSH-2.0-OpenSSH_7.4",
    "ssh_version": 2.0,
    "os": "unknown",
    "os_cpe": "o:unknown",
    "ssh_lib": "openssh",
    "ssh_lib_cpe": "a:openssh:openssh:7.4",
    "key_algorithms": [
      "curve25519-sha256@libssh.org",
      "ecdh-sha2-nistp521",
      "ecdh-sha2-nistp384",
      "ecdh-sha2-nistp256",
      "diffie-hellman-group-exchange-sha256"
    ],
    "encryption_algorithms_client_to_server": [
      "chacha20-poly1305@openssh.com",
      "aes256-gcm@openssh.com",
      "aes128-gcm@openssh.com",
      "aes256-ctr",
      "aes192-ctr",
      "aes128-ctr"
    ],
    "encryption_algorithms_server_to_client": [
      "chacha20-poly1305@openssh.com",
      "aes256-gcm@openssh.com",
      "aes128-gcm@openssh.com",
      "aes256-ctr",
      "aes192-ctr",
      "aes128-ctr"
    ],
    "mac_algorithms_client_to_server": [
      "hmac-sha2-512-etm@openssh.com",
      "hmac-sha2-256-etm@openssh.com",
      "umac-128-etm@openssh.com",
      "hmac-sha2-512",
      "hmac-sha2-256",
      "umac-128@openssh.com"
    ],
    "mac_algorithms_server_to_client": [
      "hmac-sha2-512-etm@openssh.com",
      "hmac-sha2-256-etm@openssh.com",
      "umac-128-etm@openssh.com",
      "hmac-sha2-512",
      "hmac-sha2-256",
      "umac-128@openssh.com"
    ],
    "compression_algorithms_client_to_server": [
      "none",
      "zlib@openssh.com"
    ],
    "compression_algorithms_server_to_client": [
      "none",
      "zlib@openssh.com"
    ],
    "languages_client_to_server": [

    ],
    "languages_server_to_client": [

    ],
    "auth_methods": [
      "publickey"
    ],
    "fingerprints": {
      "rsa": {
        "known_bad": "false",
        "md5": "fc:c5:5b:0d:f0:c6:fd:fe:80:18:62:2c:05:38:20:8a",
        "sha1": "e1:3c:71:49:80:37:87:32:b5:0c:e3:86:41:ef:2e:2a:2f:14:e3:58",
        "sha256": "68:7d:30:37:67:2c:eb:1e:4a:b5:ff:4f:bc:8c:e8:41:e1:55:a8:30:42:e0:8e:3c:e3:0a:ba:bc:db:fd:5c:50"
      }
    },
    "duplicate_host_key_ips": [

    ],
    "compliance": {
      "policy": "Mozilla Modern",
      "compliant": true,
      "recommendations": [

      ],
      "references": [
        "https://wiki.mozilla.org/Security/Guidelines/OpenSSH"
      ],
      "grade": "A"
    },
    "start_time": "2019-01-17 08:50:56 -0500",
    "end_time": "2019-01-17 08:50:58 -0500",
    "scan_duration_seconds": 2.169918
  }
]

**Comment by claudijd** [comment]
I don't have a working example to repro against, but I think this is caused by a case where ssh-keyscan doesn't return any stdout and stdout in the thread is nil, and thus this causes a not method when we attempt to concat it with a string object.

I pulled together this PR to fix that possible case in https://github.com/mozilla/ssh_scan/pull/478

However, I'd love to see a public case of this so I know it fixes the behavior before I cut 0.0.38 bug fix release to fix the 0.0.37 bug fix release.

Also, yo dawg!

**Comment by claudijd** [comment]
Ok, so I pushed a pre-release gem ("0.0.38.pre"), which should be available in the latest Docker image and also via RubyGems.

# How to install via rubygems
gem install ssh_scan --pre

# How to install via docker
Basically pull the latest and try again

Please do let me know if this fixes this issue for you all and I will cut 0.0.38 immediately to make it more generally available.

Thanks again for the report!

**Comment by Allaman** [comment]
The docker version is fixed! 
Unfortunately, i cannot test the RubyGems version

**Comment by claudijd** [comment]
https://github.com/mozilla/ssh_scan/releases/tag/0.0.38 has been released to fix this.  It may take a few min for the Docker images to start reporting 0.0.38, but according to @Allaman the fix is already there.  RubyGems should also have 0.0.38 live now.

**Comment by claudijd** [comment]
Thanks again for your quick feedback on getting this sorted out!

**Comment by claudijd** [comment]
https://twitter.com/claudijd/status/1085909653370929153

**Comment by exploide** [comment]
Sorry for answering late, I don't receive mails of my private GitHub account during work.

But I can confirm the issue is sorted out after updating to 0.0.38 via gem.
