### ISSUE TITLE
Refactor how fingerprints are presented in output

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#483]
This is sort of a meta issue from #482 and it also has implications for #476.

The question is what should the format look like under the fingerprints section?

Current behavior:

    "fingerprints": {
      "rsa": {
        "known_bad": "false",
        "md5": "fc:c5:5b:0d:f0:c6:fd:fe:80:18:62:2c:05:38:20:8a",
        "sha1": "e1:3c:71:49:80:37:87:32:b5:0c:e3:86:41:ef:2e:2a:2f:14:e3:58",
        "sha256": "68:7d:30:37:67:2c:eb:1e:4a:b5:ff:4f:bc:8c:e8:41:e1:55:a8:30:42:e0:8e:3c:e3:0a:ba:bc:db:fd:5c:50"
      }
    }

What should the future format/behavior be to be most useful to everyone?

**Comment by claudijd** [comment]
Idea 1:

    "fingerprints": {
      "rsa": {
        "key": "INSERT_KEY_DATA",
        "key_length": "INSERT_KEY_LENGTH",
        "known_bad": true,
      },
      "dsa": {
        "key": "INSERT_KEY_DATA",
        "key_length": "INSERT_KEY_LENGTH",
        "known_bad": true,
      }
    }

**Comment by claudijd** [comment]
@exploide feedback welcome here.

**Comment by exploide** [comment]
That looks pretty reasonable.

I guess `key` would contain the actual key data here. In idea 1 the fingerprint itself is gone. If this is the plan, maybe rename the section :wink:

On the other hand, also showing the fingerprint probably does not hurt. But I wonder if one needs the fingerprint in all hash variants. Maybe just SHA-256 is enough. But honestly I don't know. I do not make use of this information currently.

Besides I observed the current implementation outputs the fingerprint in hex format. `ssh-keygen -l` produces base64 while the RFC for SSHFP DNS records uses hex. Don't know what's more common.

**Comment by claudijd** [comment]
@exploide we could just as easily provide it in SHA-256 format, and really any common format that might be expected of really any tool to help cross-compat and comparisons.  I also agree the other hashes are probably overkill at this stage.

**Comment by claudijd** [comment]
I have a PR with changes to fix this in #484

**Comment by claudijd** [comment]
@exploide I ended up making a concession on sha256 fingerprints and I added a wrapper on it to force it back to hex format to match the others and to match the formats we expect to see in SSHFP records so it's easier compare the two for violation/etc.  See more in #490.
