### ISSUE TITLE
Automatically detect output type based on output file extension

### ISSUE THREAD

**Issue by exploide** [mozilla/ssh_scan#492]
Now that it is possible to choose between JSON and YAML, it could be further improved by automatically detecting the desired output format when giving a `--output` file path. 

E.g. `ssh_scan -o out.yaml -t example.com` currently produces JSON inside the `.yaml` file while it could know that YAML format is desired.

**Comment by claudijd** [comment]
Thanks for the suggestion, though I'd much prefer that we explicit about output formats with the output_type switch rather than doing the guessing game here.  I'm willing to be convinced otherwise, but I'm feeling like it's unneeded complexity in this case.

**Comment by claudijd** [comment]
Even though I said I don't like this, I PR'd #493 for the sake of example. 

Maybe we can still merge it, but it's not my favorite.

**Comment by exploide** [comment]
Ok, of course it is up to you to decide if this feature request should be rejected or not. If you don't like to introduce the required complexity into the code, feel free to close this issue. It is not really important for me.

The reasons I proposed this:

- Would make the command line call more userfriendly
- Some other tools also do this, e.g. nikto (but it's far from being a standard or something)
- Would simplify the command line call, since the longish `--output-type` can be omitted (output file is just `-o`)

**Comment by claudijd** [comment]
I was on the fence, which is why I PR'd, I'm ok with it and will land if makes life easier.
