### ISSUE TITLE
Create a pretty web-ui for ssh_scan

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#50]
Two main reasons for this:

1.) It helps make ssh_scan more approachable for the casual user that just wants to see what it can do
2.) This could serve as a reporting mechanism for self-evaluation and global stats for ssh end point configuration

Ideally, this would also plug into a queueing/job/workload engine so jobs can be tasked but are not blocking on the web-ui interface.

**Comment by jinankjain** [comment]
Are you thinking of using any framework for building the web-ui?

**Comment by claudijd** [comment]
@jinankjain I don't have any plans yet.  I would love if it were in Ruby, just because that's my strongest lang, but I'm open to ideas/suggestions/prototypes.

**Comment by marumari** [comment]
If you wanted to simply make a nice API, I could add support to it to the Observatory's web UI.

**Comment by claudijd** [comment]
@marumari the plan is to eventually have an API for programmatic access.  I would also like a simple front end for the ssh functionality, but happy to have it integrated into HTTP obs.

**Comment by marumari** [comment]
Well, it would be easy to make its own page in the Observatory, or part of the normal scan stuff.  No sense in reimplementing an entire new front end.  :)

**Comment by claudijd** [comment]
@marumari that sounds cool to me, where would I got to add the page?  I'll also freely admit my web dev skills are not strong, so I'm happy to defer to others that know more than I in that space.

**Comment by marumari** [comment]
https://github.com/mozilla/http-observatory-website

But if you can get the API going, I'd be happy to do the web dev part for you.

**Comment by claudijd** [comment]
@marumari awesome, thanks!

**Comment by jinankjain** [comment]
@claudijd For this we need to work on API structuring

**Comment by claudijd** [comment]
@jinankjain agreed, might be worth just drafting a doc/wiki on how it could work and then inviting @marumari for feedback since she might be helping us integrate with Observatory at some point.

**Comment by agaurav77** [comment]
@claudijd @jinankjain How about Rails/Sinatra for the backend? Rails might be a bit bulky though (convention over configuration ends up in a lot of unnecessary files). Sinatra might be just the thing for the API, though.

**Comment by claudijd** [comment]
I'd vote for Sinatra over Rails (rails is too heavy for this purpose IMO)

**Comment by agaurav77** [comment]
@claudijd The basic functionality could be - 

```
require 'sinatra'

get '/scan/:host' do |host|
  # scan hostname / single IP / IP Range
end

get '/scan' do
  # scan multiple hosts passed in as a JSON array
end

get '/version' do
  # get version info
end
```

Since options are usually mixed and used, I can query the GET parameters in /scan for policy file, input file, unit test file, and multiple hosts. Looks simple, should I add something more?

**Comment by marumari** [comment]
You may want to duplicate the API used in the HTTP Observatory:

https://github.com/mozilla/http-observatory/blob/master/httpobs/docs/api.md

**Comment by claudijd** [comment]
Because the API and workload management may be completed by different teams/people, perhaps we can start with an interface for tasking that looks like the Observatory's "Invoke" technique, but also immediately return results until the workload/job piece is completed.  Once the workload piece is done, we can change the behavior from immediate results to results you need to retrieve manually.

On a practical level though, I think we should start with docs first and then write the code that matches that behavior.  Perhaps we just copy the api markdown from httpobs and customize to our needs.  Once we all agree on the interface, building it should be trivial.

**Comment by agaurav77** [comment]
I think the API I proposed is almost like the invoke API in HTTP Observatory. I'd like to give some examples (requests would go urlencoded) -

'/scan?target=www.mozilla.com:22' => ssh_scan -t www.mozilla.com:22
'/scan?target=192.168.0.1' => ssh_scan -t 192.168.0.1
'/scan?target=192.168.0.0/24' => ssh_scan -t 192.168.0.0/24
'/scan?targets=[192.168.0.1:23, 192.168.0.2:33]' => ssh_scan -t 192.168.0.1:23 -t 192.168.0.2:33

POST parameters could be
* port (translates to -p)
* from_json (file)
* policy (file)
* threads (translates to --threads)
* unit test file (translates to -u)

'/version' => {"version":<version>}

I can start by doing a PR that creates docs/api.doc (just like in HTTP Observatory). Anything I missed?

**Comment by claudijd** [comment]
@agaurav77 please include the api version in the base of the url so we can have breaking changes down the road.  I also think that in the first iteration that we should only support single target with or without port specification, all other options should be excluded to keep it simple.

**Comment by marumari** [comment]
FYI, it should be /__version__, as that's a weird internal Mozilla standard.  It should mimic this:

https://http-observatory.security.mozilla.org/__heartbeat__   <-- this is intended to check all dependencies, returns 500 if they're not available, 200 if so
https://http-observatory.security.mozilla.org/__lbheartbeat__  <-- simply returns nothing, to indicate that it's up, simply returns a blank page with 200
https://http-observatory.security.mozilla.org/__version__  <-- returns the version and source URL

**Comment by marumari** [comment]
Note that you can still have /version, but you should also have /\_\_version\_\_

**Comment by agaurav77** [comment]
@claudijd @jinankjain @marumari I added an initial version of the API markdown file. Please review, thanks!

**Comment by claudijd** [comment]
@agaurav77 reviewed the proposal and added some comments.  Thanks!

**Comment by claudijd** [comment]
We use Mozilla Observatory for this, no need at this point to add another front end to support.
