### ISSUE TITLE
Need a new demonstration video recording to link to

### ISSUE THREAD

**Issue by pabloab** [mozilla/ssh_scan#503]
The [asciinema video of the README.md](https://github.com/mozilla/ssh_scan/blame/master/README.md#L86) return HTTP status 410, it was archived, maybe because it wasn't associated to an account. @knweiss blame point to you :-)

**Comment by claudijd** [comment]
I think I created that video when we first started with the MOSS uplift project.  It was actually quite outdated anyways from what the project does now.  I'm actually fine with leaving it for the time being.  If someone would like to do another how-to video, I'm happy to land it in it's place.
