### ISSUE TITLE
Add moar OS guessing logic

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#51]
Add OS fingerprinting logic to ssh_scan.  Two main mechanisms for doing so are...

1.) SSH banner detection as I described in this blog post from 2013 (https://www.trustwave.com/Resources/SpiderLabs-Blog/Fingerprinting-Ubuntu-OS-Versions-using-OpenSSH/)
2.) Cipher preference ordering (this could be for OS detection and SSH lib detection - openssh vs. libssh, etc.)

**Comment by claudijd** [comment]
https://github.com/mozilla/ssh_scan/pull/52 does a decent job of getting a foot in the door on the first mechanism.  Although it will need significant expansion to include supporting OS and SSH library versioning and other interesting elements.

**Comment by claudijd** [comment]
For the banner understanding, we should probably just go through all the SSH banner data for sonar and make sure we understand them all (https://scans.io/ and search for port 22 downloads)

**Comment by claudijd** [comment]
I did a quick munging of the first 2000 uniq SSH banners to help us with fingerprinting when someone is ready to take a look and start adding OS detection for OpenSSH banners
[banners_ssh.txt](https://github.com/mozilla/ssh_scan/files/407664/banners_ssh.txt)

**Comment by claudijd** [comment]
Added more examples and scaffolding for this in https://github.com/mozilla/ssh_scan/pull/63

**Comment by claudijd** [comment]
{
      "ssh_scan_version": "0.0.7",
      "hostname": "",
      "ip": "192.168.1.1",
      "port": 22,
      "error": "SSHScan::Timeout: unable to reach service due to timeout"
    }

**Comment by claudijd** [comment]
@agaurav77 is looking to work on this, fyi to avoid duplicate work.

**Comment by agaurav77** [comment]
Because Debian/Ubuntu SSH banners can be used to find the original OS versions, I'm fine with writing code to actually do so. But what should be the approach for other OSes? (Even BSD systems give some indications about when they were installed/compiled)

How about I add in more such logic as we discover more kinds of banners? So are we supposed to maintain a "database" of such banners?

**Comment by claudijd** [comment]
@agaurav77 yeah, we basically need mapping logic to say this banner equals this OS (or OR at a specific version).  In the case of BSD hosts is there is enough information to get us to a reasonable OS guess then I'd say let's add mapping for those as well.  If we find the precision to be too low, we might consider just falling back to just the OS name.  I'd also prefer the mapping be in text vs. a database just so we can easily keep the changes in version control.

**Comment by claudijd** [comment]
Going to close this issue as a master issue and track individual support as separate issues so this issue doesn't live forever.
