### ISSUE TITLE
CentOS 8.2 - cannot load such file -- netaddr (LoadError)

### ISSUE THREAD

**Issue by BeCitizenSci** [mozilla/ssh_scan#521]
I'm trying to get ssh_scan installed on a default server installation of CentOS 8.2. After running ssh_scan I get: **cannot load such file -- netaddr (LoadError)**. A Google of the error didn't produce an exact answer but the Ruby version is often said to be the cause. Before I try to install another version of Ruby (I'm using the default CentOS package now), I wanted to be sure. These are the installation steps that I've done to take care of the various dependencies. 

**Installation Procedure**
dnf install git
git clone https://github.com/mozilla/ssh_scan.git
cd ssh_scan
dnf install ruby
dnf install python3-pip
pip3 install ipython
pip3 install netaddr
gem install bundler
bundle install 

**Error**
$ ./bin/ssh_scan 
Traceback (most recent call last):
        2: from ./ssh_scan:7:in `<main>'
        1: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- netaddr (LoadError)

The strange thing about this error is that the path referenced does exist, so I'm not sure why it cannot be loaded:
$ ls /usr/share/rubygems/rubygems/core_ext
kernel_gem.rb  **kernel_require.rb**

**Ruby Version**
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]

**Comment by claudijd** [comment]
This is the madness of Ruby dependancy hell.  Let me see if I can help...

For a source checkout, I'd advise adding the following after you install bundler:
- bundle install

For docker, it should just work, and satisfy the deps for you.

Let me know if that doesn't solve the problem and we'll figure it out.

**Comment by BeCitizenSci** [comment]
I'm sorry. I should have included bundle install as my last step in this bug report, as that was the last step that I preformed before I got this error. I will correct my report and investigate further.

**Comment by BeCitizenSci** [comment]
I was successful in building from source.
