### ISSUE TITLE
Redesign the policy engine

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#61]
Currently, the policy engine is a bit rigid (black/white) and probably doesn't do enough to handle the nuances people might want from it.  Here are the a couple things it should be extended to do...

1.) It should have the ability to allow, but not require some items in a given cipher-set
2.) It should have context dependent capabilities (eg. different recommendations and compliance status based on OpenSSH version?)
3.) The ability to insert a policy control for any element we know about a given SSH endpoint so we could fail on (SSH version?, OS version?, Auth methods?, fingerprints?) and not just ciphers.

**Comment by claudijd** [comment]
This might also be considered a DSL for policy expression.

Here's are examples of what policies look like now:

https://github.com/mozilla/ssh_scan/tree/master/policies

**Comment by jinankjain** [comment]
@claudijd could you please expand on the first point bit more?

**Comment by claudijd** [comment]
@jinankjain basically, we want to have more flexibility and control with the policies.  As per the DSL content, we want to way to write more expressive rules, so people can really customize their policies.

**Comment by jinankjain** [comment]
@claudijd I was specifically asking about this thing "It should have the ability to allow, but not require some items in a given cipher-set"

**Comment by jinankjain** [comment]
So what I am able to get through this is that we need some labels which say like a strict policy, lenient policy etc?

**Comment by claudijd** [comment]
@jinankjain yeah, it probably need a design strategy more than code at first.  Like, "I think these would be a good verbs/directives" and have use all weigh in on it.  Then once we're happy with terminology, we can make it in code.   Seem reasonable?  I tried a couple approaches in earlier issues, but fell short

**Comment by jinankjain** [comment]
@claudijd Totally agreed on seems more of design problem as compared to code. We have to decide on terminologies first before we start to code.

**Comment by agaurav77** [comment]
deferring to 0.1.1, #293 is closer to what we want to land in 0.1.0
