### ISSUE TITLE
Add a timeout capability and error handling/output when we can't scan an endpoint

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#64]
This addition would have both a default and a configurable command-line switch to define how long we should hang open waiting for a connection to start before we give up and timeout the scan.

This addition would also need to define some JSON output that we would send when we resulted in an error state.  We should also specify some error text and a reason for why the scan didn't complete.

    {
      "ssh_scan_version": "0.0.7",
      "hostname": "",
      "ip": "192.168.1.1",
      "port": 22,
      "error": "SSHScan::Timeout: unable to reach service due to timeout"
    }

**Comment by jinankjain** [comment]
@claudijd This could be closed now.

**Comment by claudijd** [comment]
@jinankjain thanks for the reminder, always glad to take things off the TODO list.
