### ISSUE TITLE
nit: scan_engine.rb doesn't compare class

### ISSUE THREAD

**Issue by agaurav77** [mozilla/ssh_scan#66]
Even though we support RSA for the moment, the line (in scan_engine.rb)

    unless OpenSSL::PKey::RSA

should be replaced by

    unless host_key.class == OpenSSL::PKey::RSA

This raises the error for me.

**Comment by claudijd** [comment]
Just pushed a fix for that, once it passes the CI checks, I'll land it in master.

Thank you very much for finding this!

**Comment by claudijd** [comment]
Out of curiosity, what version of Ruby are you using?

I was running ruby 2.2.3p173 and didn't generate any errors during development or during the CI build process.

**Comment by agaurav77** [comment]
I'm using Ruby 2.3.1p112, this didn't work with it.

Also, since this is too small maybe for a PR, I'll find something else as a PR I guess then :)

**Comment by claudijd** [comment]
@agaurav77 thanks, I don't have coverage for 2.3 in the travis builds, so I'll add that shortly.

**Comment by claudijd** [comment]
@agaurav77 I've added build coverage for 2.2 and 2.3 in #68 to hopefully prevent this in the future.
