### ISSUE TITLE
--port option broken?

### ISSUE THREAD

**Issue by h0lzi** [mozilla/ssh_scan#71]
with 0.0.8 and git head and net-ssh (3.2.0) --port seems to be broken. It always connects to port 22.

./ssh_scan --target IP --port port
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/socket.rb:65:in `connect': Connection refused - connect(2) (Errno::ECONNREFUSED)

**Comment by claudijd** [comment]
I just fixed this in #73 and I tested it on a custom port SSH instance to make sure it works

Output example here:

    [
      {
        "ssh_scan_version": "0.0.8",
        "hostname": "",
        "ip": "192.168.10.173",
        "port": 23,
        "server_banner": "SSH-2.0-OpenSSH_7.1p2 Debian-1",
        "ssh_version": 2.0,
        "os": "debian",
        "os_cpe": "o:debian:debian",
        "ssh_lib": "openssh",
        "ssh_lib_cpe": "a:openssh:openssh:7.1p2",
        "key_algorithms": [
          "curve25519-sha256@libssh.org",
          "ecdh-sha2-nistp256",
          "ecdh-sha2-nistp384",
          "ecdh-sha2-nistp521",
          "diffie-hellman-group-exchange-sha256",
          "diffie-hellman-group14-sha1"
        ],
        "server_host_key_algorithms": [
          "ssh-rsa",
          "ecdsa-sha2-nistp256",
          "ssh-ed25519"
        ],
        "encryption_algorithms_client_to_server": [
          "chacha20-poly1305@openssh.com",
          "aes128-ctr",
          "aes192-ctr",
          "aes256-ctr",
          "aes128-gcm@openssh.com",
          "aes256-gcm@openssh.com"
        ],
        "encryption_algorithms_server_to_client": [
          "chacha20-poly1305@openssh.com",
          "aes128-ctr",
          "aes192-ctr",
          "aes256-ctr",
          "aes128-gcm@openssh.com",
          "aes256-gcm@openssh.com"
        ],
        "mac_algorithms_client_to_server": [
          "umac-64-etm@openssh.com",
          "umac-128-etm@openssh.com",
          "hmac-sha2-256-etm@openssh.com",
          "hmac-sha2-512-etm@openssh.com",
          "hmac-sha1-etm@openssh.com",
          "umac-64@openssh.com",
          "umac-128@openssh.com",
          "hmac-sha2-256",
          "hmac-sha2-512",
          "hmac-sha1"
        ],
        "mac_algorithms_server_to_client": [
          "umac-64-etm@openssh.com",
          "umac-128-etm@openssh.com",
          "hmac-sha2-256-etm@openssh.com",
          "hmac-sha2-512-etm@openssh.com",
          "hmac-sha1-etm@openssh.com",
          "umac-64@openssh.com",
          "umac-128@openssh.com",
          "hmac-sha2-256",
          "hmac-sha2-512",
          "hmac-sha1"
        ],
        "compression_algorithms_client_to_server": [
          "none",
          "zlib@openssh.com"
        ],
        "compression_algorithms_server_to_client": [
          "none",
          "zlib@openssh.com"
        ],
        "languages_client_to_server": [

        ],
        "languages_server_to_client": [

        ],
        "auth_methods": [
          "publickey",
          "password"
        ],
        "fingerprints": {
          "md5": "0e:17:da:0a:35:76:f7:69:99:bf:85:6d:46:1f:85:ac",
          "sha1": "8e:80:d0:99:53:bb:9f:4a:21:5d:3d:df:ce:d8:2f:dd:01:b9:58:30",
          "sha256": "a3:cc:72:35:fe:8b:87:86:0e:bf:8a:37:f2:7b:ca:4a:a5:7d:42:12:5f:a0:f8:76:f2:17:3c:1f:5b:45:29:17"
        },
        "compliance": {
          "policy": "Mozilla Modern",
          "compliant": false,
          "recommendations": [
            "Remove these Key Exchange Algos: diffie-hellman-group14-sha1",
            "Remove these MAC Algos: umac-64-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, hmac-sha1"
          ]
        }
      }
    ]
