### ISSUE TITLE
Add support for IPv4 fallback when IPv6 cannot be established

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#74]
Basically, if we have an endpoint that supports both IPv6 and IPv4 on the same hostname (ssh.example.com) and that endpoint has records for both IPv6 and IPv4, but only IPv4 has a listening SSH service we will likely not handle that scenario.  This issue is to make sure ssh_scan does have the smarts to handle that gracefully.

**Comment by jinankjain** [comment]
@claudijd One way to handle this we could do first try with IPv6 version if that fails then in the catch block of that we could do for IPv4. Am I correct?

**Comment by claudijd** [comment]
@jinankjain yeah, that could work

**Comment by jinankjain** [comment]
@claudijd then I would implement that after fixing #112 #104
