### ISSUE TITLE
NoMethodError in lib/ssh_scan/scan_engine.rb:32 on ssh_scan v0.0.8

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#77]
By request of @jvehent 

"can/could ssh_scan evaluate mfa support on a ssh server?"

**Comment by jvehent** [comment]
`ssh_scan` currently does not support scanning MFA enabled servers. Here's a test of ssh.m.c
```
$ ssh_scan -t ssh.mozilla.com
/var/lib/gems/2.3.0/gems/ssh_scan-0.0.8/lib/ssh_scan/scan_engine.rb:32:in `scan': undefined method `n' for #<OpenSSL::PKey::EC::Point:0x000000016bb948> (NoMethodError)
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.8/bin/ssh_scan:90:in `<top (required)>'
	from /usr/local/bin/ssh_scan:23:in `load'
	from /usr/local/bin/ssh_scan:23:in `<main>'
```
The fact that it fails tells me there's a way to detect the presence of MFA. It would be great to identify those servers and show in the scan results that MFA is a requirement to access the server.

**Comment by claudijd** [comment]
Example of what one might see on a DUO enabled host in the encrypted channel:

    OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
    ...SNIP...
    Duo two-factor login for user@example.com

    Enter a passcode or select one of the following options:

     1. Duo Push to XXX-XXX-1234

    Passcode or option (1-1):

**Comment by claudijd** [comment]
@jvehent what version/commit version of ssh_scan are you using?  I think I may have fixed this bug in #67

**Comment by claudijd** [comment]
If you're on the gem version, you would want check like this...

    gem list | grep ssh_scan

If you want the latest released version, you can do this...

   gem update ssh_scan

**Comment by jvehent** [comment]
No love. I'm on the latest and seeing the error.
```
$ gem list | grep ssh_scan
ssh_scan (0.0.8)
```

**Comment by claudijd** [comment]
ulfr's ruby was 2.3.1p112, so I tested with the exact same version, along with 3 other separate machines and it wasn't able to reproduce the issue.  I also tested in a docker container, that worked as well.

    root@f6d3c2de63bf:/# gem install ssh_scan
    Fetching: ssh_scan-0.0.8.gem (100%)
    Successfully installed ssh_scan-0.0.8
    Parsing documentation for ssh_scan-0.0.8
    Installing ri documentation for ssh_scan-0.0.8
    Done installing documentation for ssh_scan after 0 seconds
    1 gem installed
    root@f6d3c2de63bf:/# ruby -v
    ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
    root@f6d3c2de63bf:/# ssh_scan -t ssh.mozilla.com
    {
      "ssh_scan_version": "0.0.8",
      "hostname": "ssh.mozilla.com",
      "ip": "63.245.214.149",
      "port": 22,
      "server_banner": "SSH-2.0-OpenSSH_6.6.1",
      "ssh_version": 2.0,
      "os": "unknown",
      "os_cpe": "o:unknown",
      "ssh_lib": "openssh",
      "ssh_lib_cpe": "a:openssh:openssh",
      "key_algorithms": [
        "curve25519-sha256@libssh.org",
        "ecdh-sha2-nistp256",
        "ecdh-sha2-nistp384",
        "ecdh-sha2-nistp521",
        "diffie-hellman-group-exchange-sha256",
        "diffie-hellman-group-exchange-sha1",
        "diffie-hellman-group14-sha1",
        "diffie-hellman-group1-sha1"
      ],
      "server_host_key_algorithms": [
        "ssh-rsa",
        "ecdsa-sha2-nistp256",
        "ssh-ed25519"
      ],
      "encryption_algorithms_client_to_server": [
        "aes128-ctr",
        "aes192-ctr",
        "aes256-ctr",
        "arcfour256",
        "arcfour128",
        "aes128-gcm@openssh.com",
        "aes256-gcm@openssh.com",
        "chacha20-poly1305@openssh.com",
        "aes128-cbc",
        "3des-cbc",
        "blowfish-cbc",
        "cast128-cbc",
        "aes192-cbc",
        "aes256-cbc",
        "arcfour",
        "rijndael-cbc@lysator.liu.se"
      ],
      "encryption_algorithms_server_to_client": [
        "aes128-ctr",
        "aes192-ctr",
        "aes256-ctr",
        "arcfour256",
        "arcfour128",
        "aes128-gcm@openssh.com",
        "aes256-gcm@openssh.com",
        "chacha20-poly1305@openssh.com",
        "aes128-cbc",
        "3des-cbc",
        "blowfish-cbc",
        "cast128-cbc",
        "aes192-cbc",
        "aes256-cbc",
        "arcfour",
        "rijndael-cbc@lysator.liu.se"
      ],
      "mac_algorithms_client_to_server": [
        "hmac-md5-etm@openssh.com",
        "hmac-sha1-etm@openssh.com",
        "umac-64-etm@openssh.com",
        "umac-128-etm@openssh.com",
        "hmac-sha2-256-etm@openssh.com",
        "hmac-sha2-512-etm@openssh.com",
        "hmac-ripemd160-etm@openssh.com",
        "hmac-sha1-96-etm@openssh.com",
        "hmac-md5-96-etm@openssh.com",
        "hmac-md5",
        "hmac-sha1",
        "umac-64@openssh.com",
        "umac-128@openssh.com",
        "hmac-sha2-256",
        "hmac-sha2-512",
        "hmac-ripemd160",
        "hmac-ripemd160@openssh.com",
        "hmac-sha1-96",
        "hmac-md5-96"
      ],
      "mac_algorithms_server_to_client": [
        "hmac-md5-etm@openssh.com",
        "hmac-sha1-etm@openssh.com",
        "umac-64-etm@openssh.com",
        "umac-128-etm@openssh.com",
        "hmac-sha2-256-etm@openssh.com",
        "hmac-sha2-512-etm@openssh.com",
        "hmac-ripemd160-etm@openssh.com",
        "hmac-sha1-96-etm@openssh.com",
        "hmac-md5-96-etm@openssh.com",
        "hmac-md5",
        "hmac-sha1",
        "umac-64@openssh.com",
        "umac-128@openssh.com",
        "hmac-sha2-256",
        "hmac-sha2-512",
        "hmac-ripemd160",
        "hmac-ripemd160@openssh.com",
        "hmac-sha1-96",
        "hmac-md5-96"
      ],
      "compression_algorithms_client_to_server": [
        "none",
        "zlib@openssh.com"
      ],
      "compression_algorithms_server_to_client": [
        "none",
        "zlib@openssh.com"
      ],
      "languages_client_to_server": [

      ],
      "languages_server_to_client": [

      ],
      "auth_methods": [
        "publickey"
      ],
      "fingerprints": {
        "md5": "79:74:97:38:40:86:e4:72:a2:c3:ab:3c:44:13:01:40",
        "sha1": "cb:f5:4b:3e:b6:1d:87:e9:97:75:36:71:5f:c4:e0:ef:03:03:bc:f9",
        "sha256": "52:4c:ae:b0:00:6b:0a:74:78:27:7e:e7:1e:42:7d:61:86:5c:42:a3:64:a1:3c:8a:0b:a3:86:d4:39:28:ac:bd"
      },
      "compliance": {
        "policy": "Mozilla Modern",
        "compliant": false,
        "recommendations": [
          "Remove these Key Exchange Algos: diffie-hellman-group-exchange-sha1, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1",
          "Remove these MAC Algos: hmac-md5-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64-etm@openssh.com, hmac-ripemd160-etm@openssh.com, hmac-sha1-96-etm@openssh.com, hmac-md5-96-etm@openssh.com, hmac-md5, hmac-sha1, umac-64@openssh.com, hmac-ripemd160, hmac-ripemd160@openssh.com, hmac-sha1-96, hmac-md5-96",
          "Remove these Encryption Ciphers: arcfour256, arcfour128, aes128-cbc, 3des-cbc, blowfish-cbc, cast128-cbc, aes192-cbc, aes256-cbc, arcfour, rijndael-cbc@lysator.liu.se"
        ]
      }
    }

**Comment by claudijd** [comment]
@jvehent any chance you are running ssh_scan "binary" while also in the root of the cloned checkout?  If not, I may ask to get access to the test box to troubleshoot further.

**Comment by claudijd** [comment]
I think this bug can be traced back to #67, which was not fixed in ssh_scan v0.0.8.  I'm going to produce a pre release of v0.0.9 that should allow you to update and see if that fixes the issue.  I believe the behavior in this case is that we'd want to throw and exception stating that the host key type is unsupported at this time.  I also think it has nothing to do with MFA support and more just the host key support.

**Comment by claudijd** [comment]
@jvehent please test this beta release on your install by running the following commands...

    gem install ssh_scan --pre
    ssh_scan -t ssh.mozilla.com

It should pull down a near copy of master with the fix for #67 in place and run a scan against the said target.  Please let me know what the results are.

**Comment by claudijd** [comment]
I just fixed another bug in #81, going to send you another beta evolution shortly to test with

**Comment by claudijd** [comment]
ok, same instructions as above, version is now 0.0.9.beta.2

**Comment by jvehent** [comment]
No love... I removed the github repo and uninstall other versions of ssh_scan, still I woudn't rule out an issue between chair and keyboard on my side...

```
$ sudo gem install ssh_scan --pre
[sudo] password for ulfr: 
Fetching: ssh_scan-0.0.9.beta.2.gem (100%)
Successfully installed ssh_scan-0.0.9.beta.2
Parsing documentation for ssh_scan-0.0.9.beta.2
Installing ri documentation for ssh_scan-0.0.9.beta.2
Done installing documentation for ssh_scan after 0 seconds
1 gem installed

$ ssh_scan -t ssh.mozilla.com
/var/lib/gems/2.3.0/gems/ssh_scan-0.0.9.beta.2/lib/ssh_scan/scan_engine.rb:30:in `block in scan': Unknown host key type, need to add this host_key type (RuntimeError)
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.9.beta.2/lib/ssh_scan/scan_engine.rb:15:in `each'
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.9.beta.2/lib/ssh_scan/scan_engine.rb:15:in `each_with_index'
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.9.beta.2/lib/ssh_scan/scan_engine.rb:15:in `scan'
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.9.beta.2/bin/ssh_scan:112:in `<top (required)>'
	from /usr/local/bin/ssh_scan:23:in `load'
	from /usr/local/bin/ssh_scan:23:in `<main>'
```

**Comment by claudijd** [comment]
@jvehent actually, that fixed the one issue, and we're on to the next one, the lack of host-key support for OpenSSL::PKey::EC.  I'll try to get that part sorted shortly and then we can re-test.

**Comment by claudijd** [comment]
ok, version is now 0.0.9.beta.3, please try again

    gem update ssh_scan --pre

**Comment by jvehent** [comment]
Success! Thanks @claudijd

**Comment by claudijd** [comment]
Please note the fingerprints should be nil'd out for the time being until I sort that bit out in #84
