### ISSUE TITLE
Abstract host key fingerprint generation out of scan_engine into it's own thing

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#84]
Here's some basic guidelines...

1.) Must support RSA, DSA, and ECDSA
2.) Must generate md5, sha1, and sha256 fingeprints (with an eye toward other fingerprint styles in use or upcoming)
3.) Must be fully spec'd out so we easily prove in unit-tests that our coverage is good and works as expected (perhaps even using openssh/openssl as a verification point before we lock in the fingerprints in the specs)
4.) Must have a soft-failure mechanism when the host key type is unsupported and then send a warning to the command-line much like the current implementation does

**Comment by flash1452** [comment]
@claudijd I would like to work on this issue.

**Comment by claudijd** [comment]
@flash1452 sounds good, give it a whirl.  Thanks!
