### ISSUE TITLE
Add the ability to detect MFA's | DUO'd SSH endpoints

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#86]
Not really sure if this would work in all configurations, but depending on the auth scheme it might be possible for the user to see a DUO prompt in the encrypted channel and if so, we should report it and maybe even parse the options it provides.

**Comment by jinankjain** [comment]
@claudijd Do we any example where we could test what exactly is the output that we get when we try to ssh on such servers?

**Comment by claudijd** [comment]
@jinankjain I don't have a publicly available example to share.  This issue might need to be resolved by someone with access to a DUO-enabled ssh server.

**Comment by jinankjain** [comment]
@claudijd Could we create some server with DUO enabled for testing purpose?

**Comment by claudijd** [comment]
@jinankjain if you have the ability to do so, that would be great, I think what makes this one a little harder is that there may be an initial auth requirement.  I don't have the ability/bandwidth to stand one up right now.

**Comment by jinankjain** [comment]
I do have some publicly accessible server but I don't know how hard it
would be to configure it with duo?

**Comment by claudijd** [comment]
Check here, there might be details that can help you => https://wiki.mozilla.org/Security/Guidelines/OpenSSH#OpenSSH_server

**Comment by claudijd** [comment]
Not sure if DUO has a free tier.

**Comment by claudijd** [comment]
Going to bail on this for now, to clean up issue backlog.
