### ISSUE TITLE
`negotiate': could not settle on encryption_client algorithm

### ISSUE THREAD

**Issue by dguido** [mozilla/ssh_scan#93]
`ssh_scan` works on a few of my hosts but one in particular crashes it. The stacktrace and the config from the server are below. The scanning machine is Ubuntu 16.04.

```
# ssh_scan -t localhost
/var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:334:in `negotiate': could not settle on encryption_client algorithm (Net::SSH::Exception)
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:310:in `negotiate_algorithms'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:205:in `proceed!'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:154:in `accept_kexinit'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `loop'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `poll_message'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:223:in `loop'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:223:in `wait'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:88:in `initialize'
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.9/lib/ssh_scan/scan_engine.rb:21:in `new'
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.9/lib/ssh_scan/scan_engine.rb:21:in `block in scan'
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.9/lib/ssh_scan/scan_engine.rb:15:in `each'
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.9/lib/ssh_scan/scan_engine.rb:15:in `each_with_index'
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.9/lib/ssh_scan/scan_engine.rb:15:in `scan'
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.9/bin/ssh_scan:117:in `<top (required)>'
	from /usr/local/bin/ssh_scan:23:in `load'
	from /usr/local/bin/ssh_scan:23:in `<main>'
```

```
PasswordAuthentication no
UseDNS no
KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
```

**Comment by claudijd** [comment]
@dguido thanks for your report and the config, it was helpful in quickly reproducing the bug.

I believe the source of the bug is with the net-ssh library, which doesn't seem to have full SSH support for the encryption ciphers you are using.  Currently, ssh_scan is straddling two ssh implementations; a native implementation fully owned by this project and the net-ssh implementation to help out with the more involved SSH behavior that has yet to be natively implemented.  So, it would be possible for ssh_scan to handle some of the basic stuff (like encryption algos, macs, os detection, ssh lib detection, etc.) but would fail at the stuff we're using net-ssh for ATM (auth method detection, RSA fingerprint detection) if we wanted to work around this by providing partial results that don't require full negotiation.

I did test net-ssh by itself and did run into the same issue you described above...

    $ irb
    2.2.3 :001 > require 'net/ssh'
     => true 
    2.2.3 :002 > Net::SSH.start('192.168.10.173')
    Net::SSH::Exception: could not settle on encryption_client algorithm
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:334:in `negotiate'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:310:in `negotiate_algorithms'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:205:in `proceed!'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:154:in `accept_kexinit'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `loop'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `poll_message'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:223:in `loop'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:223:in `wait'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:88:in `initialize'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-3.2.0/lib/net/ssh.rb:232:in `new'
    	from /Users/jclaudius/.rvm/gems/ruby-2.2.3/gems/net-ssh-3.2.0/lib/net/ssh.rb:232:in `start'
    	from (irb):2
    	from /Users/jclaudius/.rvm/rubies/ruby-2.2.3/bin/irb:15:in `<main>'

It seems as though the source of the issue is the encryption algos that you are using and the ones that net-ssh supports by are mutually exclusive:

**From net-ssh's ssh/transport/algorithms.rb:32-45**

      :encryption  => %w(aes128-cbc 3des-cbc blowfish-cbc cast128-cbc
                         aes192-cbc aes256-cbc rijndael-cbc@lysator.liu.se
                         idea-cbc none arcfour128 arcfour256 arcfour
                         aes128-ctr aes192-ctr aes256-ctr
                         camellia128-cbc camellia192-cbc camellia256-cbc
                         camellia128-cbc@openssh.org
                         camellia192-cbc@openssh.org
                         camellia256-cbc@openssh.org
                         camellia128-ctr camellia192-ctr camellia256-ctr
                         camellia128-ctr@openssh.org
                         camellia192-ctr@openssh.org
                         camellia256-ctr@openssh.org
                         cast128-ctr blowfish-ctr 3des-ctr
                        ),

**From your config's encryption types**

    chacha20-poly1305@openssh.com
    aes256-gcm@openssh.com
    aes128-gcm@openssh.com

It does seem as though net-ssh is working on support for these encryption types, but they just aren't there yet.  Here are some issues I was able to dredge up to help with context...

- https://github.com/net-ssh/net-ssh/issues/214 (RE: chacha20-poly1305 - currently unsupported)
- https://github.com/net-ssh/net-ssh/commit/e77d7b799a77f6de85f4f337e8483194d47b68df (RE:  aes128-gcm@openssh.com and aes128-gcm@openssh.com - currently unsupported)

I suspect they will add them in due time, and when they do I can make sure the minimum version of net-ssh required to run this code is higher than that to ensure they are supported in ssh_scan when net-ssh supports them.

Also, I'm considering providing a partial scan result for use cases like this where we can negotiate what the server wants to talk in the kex_init even if we don't have the smarts to negotiate and handle the full setup that would give use fingerprints and auth_methods.  I hope to have a work around for you shortly.

Again, thanks for the report, it's very helpful to understand where the limits of net-ssh are and be able to work around those gaps until net-ssh is able to fix them or I'm able to implement the feature set natively.

**Comment by dguido** [comment]
> Also, I'm considering providing a partial scan result for use cases like this where we can negotiate what the server wants to talk in the kex_init even if we don't have the smarts to negotiate and handle the full setup that would give use fingerprints and auth_methods. I hope to have a work around for you shortly.

That sounds like a good idea. I agree that printing the info you have and then cleanly exiting would be a better solution. Sucks that net-ssh isn't keeping up with new supported ciphers for SSH!

**Comment by claudijd** [comment]
Wrote up a quick fix in #94 and tested it against your proposed config.  That should achieve the behavior you're looking for.   It also looks as though by your trace above that you're using the gem installation method, I'll produce a beta release for 0.0.10 in a couple min so you can proceed with your scanning activity.

**Comment by claudijd** [comment]
If you are running the gem install, please try out this beta release with #94 patched into it to see if it works for you...

    gem install --pre ssh_scan -v="0.0.10.beta.1"

**Comment by dguido** [comment]
Works great now! Thanks!

**Comment by claudijd** [comment]
Glad to hear, let me know if you find anything else.

**Comment by dguido** [comment]
I figured you would have similar problems if I remove supported for all the "legacy" host key algorithms and I was right :>

```
root@algo:~# ssh_scan -t localhost
/var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:334:in `negotiate': could not settle on host_key algorithm (Net::SSH::Exception)
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:309:in `negotiate_algorithms'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:205:in `proceed!'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:154:in `accept_kexinit'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `loop'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `poll_message'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:223:in `loop'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:223:in `wait'
	from /var/lib/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:88:in `initialize'
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.10.beta.1/lib/ssh_scan/scan_engine.rb:26:in `new'
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.10.beta.1/lib/ssh_scan/scan_engine.rb:26:in `block in scan'
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.10.beta.1/lib/ssh_scan/scan_engine.rb:15:in `each'
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.10.beta.1/lib/ssh_scan/scan_engine.rb:15:in `each_with_index'
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.10.beta.1/lib/ssh_scan/scan_engine.rb:15:in `scan'
	from /var/lib/gems/2.3.0/gems/ssh_scan-0.0.10.beta.1/bin/ssh_scan:117:in `<top (required)>'
	from /usr/local/bin/ssh_scan:23:in `load'
	from /usr/local/bin/ssh_scan:23:in `<main>'
```

```
# HostKeys for protocol version 2
#HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_dsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
```

**Comment by claudijd** [comment]
@dguido yep, I see that I do, I'll add some more handling for this case too.

**Comment by dguido** [comment]
Sidenote: I thought there would be more server_host_key_algorithm options reported in the default configuration. I looked up the [OpenSSH manual](http://man.openbsd.org/sshd_config) and they say this is the default ordering:

```
ecdsa-sha2-nistp256-cert-v01@openssh.com, 
ecdsa-sha2-nistp384-cert-v01@openssh.com, 
ecdsa-sha2-nistp521-cert-v01@openssh.com, 
ssh-ed25519-cert-v01@openssh.com, 
ssh-rsa-cert-v01@openssh.com, 
ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521, 
ssh-ed25519,ssh-rsa
```

However, the results that come back from a default OpenSSHd (Ubuntu 16.04 without HostKeyAlgorithms defined in sshd_config), I get this as the result from ssh_scan:

```
    "server_host_key_algorithms": [
      "ssh-rsa",
      "rsa-sha2-512",
      "rsa-sha2-256",
      "ecdsa-sha2-nistp256",
      "ssh-ed25519"
    ],
```

Something doesn't make sense here...

**Comment by claudijd** [comment]
I've got a work around testing now for the host_key issue (https://github.com/mozilla/ssh_scan/pull/95)

**Comment by claudijd** [comment]
As to your question or interest in some sort of mismatch here, I think it's possible there could be a couple sources that might contribute to that...

1.) Perhaps my hard coded client key_init isn't fully fleshed out and thus the server is reflecting only a subset of what it supports (https://github.com/mozilla/ssh_scan/blob/master/lib/ssh_scan/constants.rb#L8-L21 and https://github.com/mozilla/ssh_scan/blob/master/spec/ssh_scan/protocol_spec.rb#L22-L97)

2.) Perhaps the openssh binary bundled with ubuntu has different defaults that don't match the documentation

**Comment by dguido** [comment]
Hm yeah I'm modifying the HostKeyAlgorithms and not really seeing the output I expect from ssh_scan. Might have to revisit this later.

**Comment by claudijd** [comment]
@dguido please do, I would love to hear what you find out and whether it's a bug in ssh_scan or in the openssh configuration settings

**Comment by claudijd** [comment]
Also, I've built another beta release for you to work around the problem that we fixed in (#95)

    gem install --pre ssh_scan -v="0.0.10.beta.2"

**Comment by dguido** [comment]
Cool, works again. Thanks!

**Comment by claudijd** [comment]
With all host-keys commented out, I got the following host-keys supported using "OpenSSH_7.1p2 Debian-1"...

    "server_host_key_algorithms": [
      "ssh-rsa",
      "ecdsa-sha2-nistp256",
      "ssh-ed25519"
    ],

With just one of them enabled, I was able to see a direct change in output...

    "server_host_key_algorithms": [
      "ssh-ed25519"
    ],

**Comment by claudijd** [comment]
I did notice when I enabled DSA it didn't show up in the scan result, but I verified on the wire that DSA was not provided in the kex_init response from server, so this doesn't seem like a ssh_scan interpretation issue.

**Comment by athiraramanan** [comment]
Hi We are trying to upload a file from the local repository  to remote and stuck on one issue
with Net::SSH::Exception: could not settle on encryption_client algorithm
Server encryption_client preferences: 3des-cbc,aes128-cbc
Client encryption_client preferences: aes256-ctr,aes192-ctr,aes128-ctr

**Comment by claudijd** [comment]
@athiraramanan I can't tell if you are using Net::SSH to upload content or if you are trying to perform an ssh_scan, but either way, I think I can offer some help what you are showing here and make some guesses as to what is happening...

I think what's happening in your case is that you have a server which is running a rather old set of SSH encryption preferences and the client in this case Net::SSH is offering a more modern set of client preferences.

Software projects like ssh_scan utilize Net::SSH to do some of the heavy lifting of an SSH session.  In the case of ssh_scan, we set these parameters here:

https://github.com/mozilla/ssh_scan/blob/master/lib/ssh_scan/constants.rb#L16-L19

They are then loaded here, to monkey patch the defaults for Net::SSH:

https://github.com/mozilla/ssh_scan/blob/master/lib/ssh_scan.rb#L8

I suppose if Net::SSH (at whatever version you are using) still had the primatives for those older cipher sets you might be able to get away with patching those additional cipher sets into the constants list.

If you have a public instance or can make one that mimics the server preferences above, we could totally just test it, let me know if you have a public instance we can test this with and I'll try it out.
